-- Query per inserire tutte le macro categorie -->
INSERT INTO macro_category (name)
VALUES ('Grafica & Design'),
       ('Programmazione'),
       ('Marketing'),
       ('Video & Animazioni'),
       ('Audio & Musica'),
       ('Business'),
       ('Finanza'),
       ('Consulenza'),
       ('Fotografia');

-- Query per inserire tutte le sotto categorie -->
INSERT INTO sub_category (name, macro_category_id)
VALUES
    -- Grafica & Design
    ('Loghi e Branding', 1),
    ('Web e App Design', 1),
    ('Design di Siti Web', 1),
    ('UX e UI Design', 1),
    ('Icone e Simboli', 1),
    ('Grafica per Prodotti e Giochi', 1),
    ('Grafica per Streaming', 1),
    ('Game Art e Personaggi', 1),
    ('Illustrazioni e Disegni', 1),
    ('Copertine e Packaging', 1),
    ('Brochure e Materiale Promozionale', 1),
    ('Infografiche', 1),
    ('Design di Banner', 1),
    ('Biglietti da Visita', 1),
    ('Flyer e Locandine', 1),
    ('Identità Visiva', 1),
    ('Animazione 2D e 3D', 1),
    ('Mockup di Prodotto', 1),

    -- Programmazione
    ('AI e Machine Learning', 2),
    ('Chatbot AI', 2),
    ('Integrazione AI', 2),
    ('Bot per Social Media', 2),
    ('Risoluzione di Bug e Debugging', 2),
    ('Backup e Migrazione', 2),
    ('Sviluppo Cross-Platform', 2),
    ('Sviluppo App iOS e Android', 2),
    ('Manutenzione App Mobile', 2),
    ('Conversione Sito a App', 2),
    ('Sviluppo VR e AR', 2),
    ('Cloud Computing e Infrastruttura', 2),
    ('Sviluppo Applicazioni Web', 2),
    ('Gestione Database', 2),
    ('Sviluppo Full Stack', 2),

    -- Marketing
    ('Social Media Marketing', 3),
    ('Ottimizzazione SEO', 3),
    ('Content e Email Marketing', 3),
    ('Pay Per Click (PPC)', 3),
    ('Affiliate Marketing', 3),
    ('Ricerca di Mercato', 3),
    ('Branding e Strategie', 3),
    ('Gestione Community', 3),
    ('Growth Hacking', 3),
    ('Pubbliche Relazioni', 3),
    ('Lead Generation', 3),
    ('E-commerce Marketing', 3),
    ('SEO Locale e Audit', 3),
    ('Campagne Pubblicitarie', 3),

    -- Video & Animazioni
    ('Animazione Video e 3D', 4),
    ('Montaggio Video', 4),
    ('Video Musicali e Effetti', 4),
    ('Intro e Outro Video', 4),
    ('Presentazioni Animate', 4),
    ('Animazione di Loghi', 4),
    ('Video per Social Media', 4),
    ('Video Esplicativi e Aziendali', 4),
    ('Motion Graphics', 4),
    ('Spot Pubblicitari', 4),
    ('Animazione Cartoon', 4),
    ('Green Screen e Storyboard', 4),
    ('Video per Crowdfunding', 4),

    -- Audio & Musica
    ('Produzione Musicale e Mixaggio', 5),
    ('Mastering e Sound Design', 5),
    ('Editing Audio e Podcast', 5),
    ('Voice Over e Jingle', 5),
    ('Registrazione Voci', 5),
    ('Composizione e Beat Making', 5),
    ('Lezioni di Musica', 5),
    ('Restauro Audio e Effetti', 5),
    ('Colonne Sonore', 5),
    ('Musica per Giochi', 5),
    ('Trascrizione Audio', 5),

    -- Business
    ('Piani Aziendali', 6),
    ('Presentazioni e Formazione', 6),
    ('Consulenza Legale', 6),
    ('Outsourcing e Project Management', 6),
    ('Ricerche di Mercato', 6),
    ('Trasformazione Digitale', 6),
    ('Analisi Dati e Qualità', 6),
    ('Assistenza Clienti e Lead Management', 6),
    ('Compliance e Amministrazione', 6),
    ('Coaching e Traduzioni', 6),

    -- Finanza
    ('Consulenza Finanziaria', 7),
    ('Investimenti e Contabilità', 7),
    ('Pianificazione e Fiscalità', 7),
    ('Consulenza Assicurativa', 7),
    ('Finanza Personale e Credito', 7),
    ('Mutui e Patrimoni', 7),
    ('Consulenza Criptovalute', 7),
    ('Corsi di Finanza', 7),
    ('Gestione Budget', 7),
    ('Consulenza Fintech', 7),

    -- Consulenza
    ('Consulenza Strategica', 8),
    ('Consulenza IT', 8),
    ('Consulenza Marketing', 8),
    ('Consulenza HR e Legale', 8),
    ('Consulenza Tecnica', 8),
    ('Consulenza Ambientale', 8),
    ('Consulenza Educativa', 8),
    ('Consulenza Imprenditoriale', 8),
    ('Consulenza Alimentare e Psicologica', 8),
    ('Consulenza Farmaceutica', 8),
    ('Consulenza Startup', 8),
    ('Consulenza Salute e Immobiliare', 8),
    ('Consulenza Eventi e Bandi', 8),

    -- Fotografia
    ('Fotografia Prodotti e Ritratti', 9),
    ('Fotografia Eventi e Paesaggi', 9),
    ('Fotografia Matrimonio e Sportiva', 9),
    ('Fotografia Moda e Architettura', 9),
    ('Fotografia Aziendale e E-commerce', 9),
    ('Fotografia Interni', 9),
    ('Editing e Restauro Fotografico', 9),
    ('Fotografia con Droni', 9),
    ('Fotografia Naturalistica', 9),
    ('Fotografia per Social Media', 9),
    ('Fotografia Pubblicitaria e Editoriale', 9),
    ('Fotografia di Cibo', 9);

-- Query per inserire tutte le tag -->
INSERT INTO tag (name)
VALUES
    -- Grafica & Design
    ('Loghi'),
    ('Design UX/UI'),
    ('Web design'),
    ('Icone'),
    ('Illustrazioni'),
    ('Brochure'),
    ('Biglietti da visita'),
    ('Packaging'),
    ('Animazione 2D'),
    ('Animazione 3D'),
    ('Mockup'),
    ('Character design'),
    ('Grafica per streaming'),
    ('Game art'),
    ('Photoshop editing'),
    ('Rendering 3D'),
    ('Modelli CAD'),
    ('Design vettoriale'),
    ('Creazione GIF'),

    -- Programmazione
    ('Machine Learning'),
    ('AI'),
    ('Chatbot'),
    ('Social Media Bot'),
    ('Debugging'),
    ('Backup'),
    ('App iOS'),
    ('App Android'),
    ('Sviluppo VR'),
    ('Sviluppo AR'),
    ('Full stack'),
    ('Web app'),
    ('Cloud computing'),
    ('Database'),
    ('Sviluppo cross-platform'),
    ('API integration'),
    ('Sicurezza informatica'),
    ('Blockchain development'),
    ('Server management'),
    ('E-commerce development'),

    -- Marketing
    ('Social media'),
    ('SEO'),
    ('Content marketing'),
    ('PPC'),
    ('Affiliate marketing'),
    ('Strategie brand'),
    ('Lead generation'),
    ('E-commerce'),
    ('Branding'),
    ('Analisi mercati'),
    ('PR'),
    ('Community management'),
    ('Influencer marketing'),
    ('SEO tecnico'),
    ('Marketing automation'),
    ('Copywriting'),
    ('Campagne pubblicitarie'),
    ('Creazione landing page'),
    ('Analisi della concorrenza'),
    ('Strategie di fidelizzazione'),

    -- Video & Animazioni
    ('Video editing'),
    ('Video musicale'),
    ('Intro video'),
    ('Outro video'),
    ('Presentazioni animate'),
    ('Logo animation'),
    ('Video esplicativi'),
    ('Motion graphics'),
    ('Spot pubblicitari'),
    ('Cartoon animation'),
    ('Storyboard'),
    ('Crowdfunding video'),
    ('Editing con effetti speciali'),
    ('Montaggio cinematografico'),
    ('Post produzione video'),
    ('Creazione trailer'),
    ('Timelapse'),
    ('Sottotitoli e doppiaggio'),
    ('Video corporate'),

    -- Audio & Musica
    ('Produzione musicale'),
    ('Mixaggio'),
    ('Mastering'),
    ('Sound design'),
    ('Editing audio'),
    ('Voice over'),
    ('Registrazione'),
    ('Colonna sonora'),
    ('Beat making'),
    ('Restauro audio'),
    ('Lezioni di musica'),
    ('Composizione canzoni'),
    ('Jingles pubblicitari'),
    ('Podcast editing'),
    ('Sound effects'),
    ('Voce narrante'),
    ('Registrazione strumentale'),
    ('Cover musicali'),
    ('Sintetizzazione audio'),
    ('Ingegneria del suono'),

    -- Business
    ('Piani aziendali'),
    ('Formazione'),
    ('Consulenza legale'),
    ('Project management'),
    ('Trasformazione digitale'),
    ('Assistenza clienti'),
    ('Digitalizzazione'),
    ('Ricerca di mercato'),
    ('Qualità e analisi dati'),
    ('Compliance'),
    ('Amministrazione aziendale'),
    ('Ottimizzazione processi'),
    ('Consulenza GDPR'),
    ('Management finanziario'),
    ('Gestione team'),
    ('Controllo di gestione'),
    ('Strategia competitiva'),
    ('Lean management'),
    ('Analisi di rischio'),
    ('Benchmarking'),

    -- Finanza
    ('Investimenti'),
    ('Consulenza fiscale'),
    ('Consulenza assicurativa'),
    ('Finanza personale'),
    ('Budget'),
    ('Credito'),
    ('Criptovalute'),
    ('Fintech'),
    ('Consulenza mutui'),
    ('Pianificazione patrimoniale'),
    ('Analisi creditizia'),
    ('Crowdfunding'),
    ('Trading'),
    ('Analisi finanziaria'),
    ('Valutazione aziendale'),
    ('Gestione delle spese'),
    ('Pianificazione previdenziale'),
    ('Rendicontazione fiscale'),
    ('Gestione patrimoniale'),
    ('Ricerca di investitori'),

    -- Consulenza
    ('Consulenza strategica'),
    ('Consulenza IT'),
    ('Consulenza HR'),
    ('Consulenza ambientale'),
    ('Consulenza marketing'),
    ('Consulenza alimentare'),
    ('Consulenza psicologica'),
    ('Consulenza startup'),
    ('Consulenza salute'),
    ('Consulenza farmaceutica'),
    ('Consulenza educativa'),
    ('Consulenza eventi'),
    ('Consulenza legale aziendale'),
    ('Consulenza fiscale internazionale'),
    ('Consulenza energetica'),
    ('Consulenza immobiliare'),
    ('Consulenza gestione rifiuti'),
    ('Consulenza in sostenibilità'),
    ('Coaching aziendale'),
    ('Mentorship imprenditoriale'),

    -- Fotografia
    ('Fotografia ritratti'),
    ('Fotografia eventi'),
    ('Fotografia prodotti'),
    ('Fotografia paesaggi'),
    ('Fotografia e-commerce'),
    ('Fotografia matrimonio'),
    ('Fotografia moda'),
    ('Fotografia interni'),
    ('Restauro foto'),
    ('Fotografia con droni'),
    ('Fotografia cibo'),
    ('Fotografia pubblicitaria'),
    ('Editing fotografico avanzato'),
    ('Fotografia sportiva'),
    ('Ritocco di immagini'),
    ('Fotografia macro'),
    ('Servizi fotografici aziendali'),
    ('Fotografia bambini'),
    ('Fotografia immobiliare'),
    ('Fotografia notturna');

-- Query per inserire i carrelli degli utenti -->
INSERT INTO cart (created_date)
VALUES (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE),
       (CURRENT_DATE);

-- Query per inserire gli utenti -->
INSERT INTO users (active, email, name, surname, nickname, password, role, cart_id, ranking, fiscal_code,
                   url_user_photo, birth_date, based_in)
VALUES (true, 'ilmitico79@gmail.com', 'Dario', 'Nardella', 'Narderio',
        '$2a$10$uogVPGPCxsiJ8nXSykd2QuVliBSRRAPnkq3w/j1TnijHJk6eDTie.', 'MODERATOR', 1, 0.0, 'NRDDRA79A01H501A',
        'user_photos/img_1.png', '2003-05-17', 'Firenze'),

       (true, 'boscofabio36@gmail.com', 'Fabio', 'Bosco', 'FabWood03',
        '$2a$10$CZNL9lm.CGj9OT/CoGxU1OW.XIWmoLrJqFnrX/kO2g1a0JdQLxJPq', 'ADMIN', 2, 0.0, 'BSCFBA03T13D423X',
        'user_photos/1696238130455.jpg', '2003-12-13', 'Trapani'),

       (true, 'giadarusso3010@gmail.com', 'Giada', 'Russo', 'GiaRu3010',
        '$2a$10$Q/yNbHzrjX95Noew2fm7oOP0I3b/gqwZtcSLhDrIy/F6g3fuBnIBq', 'SELLER', 3, 4.08, 'RSGDI04335BD423X',
        'user_photos/giada_russo.png',
        '2003-10-30', 'New York'),

       (true, 'claudia.laruffa@gmail.com', 'Claudia', 'Laruffa', 'ClaLaru',
        '$2a$10$WPp9Zz8nX1vJljO4QCPSN.OBQFEoRGl2s/F3CQAQA7.73cGFBRgyG', 'SELLER', 4, 4.02, 'LRFCLD03R42H224J',
        'user_photos/claudia_laruffa.png', '2003-08-02', 'Gioia Tauro'),

       (true, 'danielecozzi2003@gmail.com', 'Daniele', 'Cozzi', 'DaniCozz',
        '$2a$10$oXKgMGylfz3E.w2baOSCcuYCqD6Z4DhdUQ5lLL9xAmgsZ/j9L5BrG', 'BUYER', 5, 0.0, null, null, null, null),

       (true, 'FiliPino@example.com', 'Filippo', 'Pino', 'FilipRand',
        '$2a$10$cx11epCJN7ueiQdcyiP9gO.RFfRqB.CIwCZV.1ytv0nnengFzEeYy', 'SELLER', 6, 3.84, 'RNDFPP24A01H501A',
        'user_photos/premium_photo-1689977927774-401b12d137d6.jpg', '2003-01-01', 'Aosta'),

       (true, 'justinRobinson@example.com', 'Justin', 'Robinson', 'JustRob',
        '$2a$10$3zMhYrt7dmuEItTUejlEluaQreyeNkIa4VRJKauHulH0LDJrNdmbC', 'BUYER', 7, 0.0, null, null, null, null),

       (true, 'mariorossi01@example.com', 'Mario', 'Rossi', 'SuperMario',
        '$2a$10$5h1H5/NnEMZRWQ5aZmzxhuJeuzJt5KOdyGwA8rQlXmTiUjoG3Etse', 'SELLER', 8, 3.92, 'RSSMRA01A01H501A',
        'user_photos/photo-1633332755192-727a05c4013d.jpg', '1999-12-01', 'Parigi'),

       (true, 'annabianchi23@example.com', 'Anna', 'Bianchi', 'AnnaBianchi1989',
        '$2a$10$JkAZ41d71Wrqs0HY6Df/8u45YY0D/eQ3ZhEMJ.5TyToIlACBC7Tdi', 'SELLER', 9, 4, 'BNCNNA23A01H501A', null,
        '1989-01-23', 'Berlino'),

       (true, 'lucaverdi77@example.com', 'Luca', 'Verdi', 'LucaGreen',
        '$2a$10$1pTeQzEuueXIsTLpiMX/He5F6kPIWQ/BHKpDJ5sClMKFP7bdH5JkO', 'SELLER', 10, 4.08, 'VRDLCA77A01H501A', null,
        '1977-01-01', 'Roma'),

       (true, 'giorgiagialli56@example.com', 'Giorgia', 'Gialli', 'GioYellow',
        '$2a$10$uogVPGPCxsiJ8nXSykd2QuVliBSRRAPnkq3w/j1TnijHJk6eDTie.', 'SELLER', 11, 3.66, 'GLLGGA56A01H501A', null,
        '1976-01-13', 'Tokyo'),

       (true, 'federicobianchi04@example.com', 'Federico', 'Bianchi', 'FedeWhite',
        '$2a$10$uogVPGPCxsiJ8nXSykd2QuVliBSRRAPnkq3w/j1TnijHJk6eDTie.', 'SELLER', 12, 4.48, 'BNCFDC04A01H501A', null,
        '1996-07-13', 'Madrid'),

       (true, 'martaferrari88@example.com', 'Marta', 'Ferrari', 'MartaF88',
        '$2a$10$uogVPGPCxsiJ8nXSykd2QuVliBSRRAPnkq3w/j1TnijHJk6eDTie.', 'BUYER', 13, 0.0, null, null, null, null),

       (true, 'alessandrorossi55@example.com', 'Alessandro', 'Rossi', 'AlexRed',
        '$2a$10$uogVPGPCxsiJ8nXSykd2QuVliBSRRAPnkq3w/j1TnijHJk6eDTie.', 'BUYER', 14, 0.0, null, null, null, null),

       (true, 'elisamartini66@example.com', 'Elisa', 'Martini', 'EllyM66',
        '$2a$10$uogVPGPCxsiJ8nXSykd2QuVliBSRRAPnkq3w/j1TnijHJk6eDTie.', 'BUYER', 15, 0.0, null, null, null, null),

       (true, 'giovannibruno99@example.com', 'Giovanni', 'Bruno', 'GioBrown',
        '$2a$10$uogVPGPCxsiJ8nXSykd2QuVliBSRRAPnkq3w/j1TnijHJk6eDTie.', 'BUYER', 16, 0.0, null, null, null, null),

       (true, 'laurapietra33@example.com', 'Laura', 'Pietra', 'LauRock',
        '$2a$10$uogVPGPCxsiJ8nXSykd2QuVliBSRRAPnkq3w/j1TnijHJk6eDTie.', 'BUYER', 17, 0.0, null, null, null, null);

-- Query per inserire tutte le abilità degli utenti -->
INSERT INTO user_skills (user_id, skills)
VALUES (3, 'Animazione'),
       (3, 'Grafica'),
       (3, 'Fotografia'),
       (4, 'Sviluppo Web'),
       (4, 'SEO'),
       (4, 'Fotografia'),
       (6, 'Produzione Audio'),
       (6, 'Sound Design'),
       (8, 'Fotografia'),
       (8, 'Eventi'),
       (8, 'Pubblicità');

-- Query per inserire tutte le lingue -->
INSERT INTO user_languages(user_id, languages)
VALUES (1, 'Italiano'),
       (1, 'Inglese'),
       (2, 'Italiano'),
       (2, 'Inglese'),
       (3, 'Italiano'),
       (3, 'Inglese'),
       (3, 'Francese'),
       (3, 'Russo'),
       (4, 'Italiano'),
       (4, 'Inglese'),
       (4, 'Spagnolo'),
       (6, 'Filippino'),
       (6, 'Italiano'),
       (6, 'Inglese'),
       (8, 'Italiano'),
       (8, 'Inglese'),
       (8, 'Rumeno'),
       (9, 'Italiano'),
       (9, 'Inglese'),
       (9, 'Cinese'),
       (10, 'Italiano'),
       (10, 'Giapponese'),
       (11, 'Italiano'),
       (11, 'Francese'),
       (11, 'Inglese'),
       (12, 'Italiano'),
       (12, 'Francese');

-- Query per inserire tutti i portfolio degli utenti -->
INSERT INTO user_portfolio (user_id, portfolio)
VALUES (3, 'portfolio/Portfolio_WithUserId_3/240610-beauty-awards-2024.jpg'),
       (3, 'portfolio/Portfolio_WithUserId_3/create_Promo-video-maker_how-to2x.jpg'),
       (3, 'portfolio/Portfolio_WithUserId_3/drugstorebeautyproducts-2048px-2858.jpg'),
       (3, 'portfolio/Portfolio_WithUserId_3/ELITAFILM++-+Video.jpg'),
       (3, 'portfolio/Portfolio_WithUserId_3/why-promo-video-important.jpeg'),
       (3, 'portfolio/Portfolio_WithUserId_3/61GHYDPSemL._AC_UY900_.jpg'),
       (4, 'portfolio/Portfolio_WithUserId_4/64fa86a1321bc75b84a33780.png'),
       (4, 'portfolio/Portfolio_WithUserId_4/27311171ca502995.jpg'),
       (4, 'portfolio/Portfolio_WithUserId_4/a14783f4-fe49-4c87-ad29.png'),
       (4, 'portfolio/Portfolio_WithUserId_4/detail-in-the-seo.jpg'),
       (4, 'portfolio/Portfolio_WithUserId_4/freepik__upload__18385.png'),
       (4, 'portfolio/Portfolio_WithUserId_4/seo-analytics-dashboard_page-0001.jpg'),
       (6, 'portfolio/Portfolio_WithUserId_6/audio-video-production-01.jpg'),
       (6, 'portfolio/Portfolio_WithUserId_6/business-growth-chart-main.jpg'),
       (6, 'portfolio/Portfolio_WithUserId_6/business-growth-model.png'),
       (6, 'portfolio/Portfolio_WithUserId_6/laptop_8e474330.jpg'),
       (6, 'portfolio/Portfolio_WithUserId_6/music-production-studio.jpg'),
       (6, 'portfolio/Portfolio_WithUserId_6/Untitled.jpg'),
       (8, 'portfolio/Portfolio_WithUserId_8/Blog00_GalaThemes_Centerpiece.png'),
       (8, 'portfolio/Portfolio_WithUserId_8/How-to-Create-an-Event-Page.jpg'),
       (8, 'portfolio/Portfolio_WithUserId_8/ICC-Belfast-Hall-1A-Tata-Genuine.jpg'),
       (8, 'portfolio/Portfolio_WithUserId_8/image3-min-1.jpg'),
       (8, 'portfolio/Portfolio_WithUserId_8/istockphoto-1340877408-612x612.jpg'),
       (8, 'portfolio/Portfolio_WithUserId_8/River+Oaks+Country+Club.jpeg'),
       (9, 'portfolio/Portfolio_WithUserId_9/commercial-video-advantages-2.jpeg'),
       (9, 'portfolio/Portfolio_WithUserId_9/commercial-video-benefits-1.jpg'),
       (9, 'portfolio/Portfolio_WithUserId_9/eligbility-criteria.jpg'),
       (9, 'portfolio/Portfolio_WithUserId_9/ogImage_Ad-Director_1.0.jpg'),
       (9, 'portfolio/Portfolio_WithUserId_9/realizzazione-video-spot.jpg'),
       (9, 'portfolio/Portfolio_WithUserId_9/video-ads_fb-img_1200x800.jpg'),
       (10, 'portfolio/Portfolio_WithUserId_10/ContenutiSEOFriendly.png'),
       (10, 'portfolio/Portfolio_WithUserId_10/scrivere-testi-seo_800x533.jpg'),
       (10, 'portfolio/Portfolio_WithUserId_10/SEO.png'),
       (10, 'portfolio/Portfolio_WithUserId_10/seo-strategy.png'),
       (10, 'portfolio/Portfolio_WithUserId_10/SEO-Strategy (1).png'),
       (10, 'portfolio/Portfolio_WithUserId_10/SEO-STRATEGY-1.png'),
       (11, 'portfolio/Portfolio_WithUserId_11/3-1.jpg'),
       (11, 'portfolio/Portfolio_WithUserId_11/brand-identity-design-style-guide.jpg'),
       (11, 'portfolio/Portfolio_WithUserId_11/design-del-logo-aziendale.jpg'),
       (11, 'portfolio/Portfolio_WithUserId_11/logotipo-profesional-de.jpg'),
       (11, 'portfolio/Portfolio_WithUserId_11/professional-corporate.jpg'),
       (11, 'portfolio/Portfolio_WithUserId_11/quanto-costa.jpg'),
       (12, 'portfolio/Portfolio_WithUserId_12/3d-rendering-abstract-building.jpg'),
       (12, 'portfolio/Portfolio_WithUserId_12/exterior-design-in-3d-architecture.jpg'),
       (12, 'portfolio/Portfolio_WithUserId_12/modellazione-3d.jpg'),
       (12, 'portfolio/Portfolio_WithUserId_12/Modellazione-3D-e-rendering.jpg'),
       (12, 'portfolio/Portfolio_WithUserId_12/ottieni-dal modello-architettonico.jpg'),
       (12, 'portfolio/Portfolio_WithUserId_12/Vista_interna_sala_14_-_sketch_up.jpg');

-- Query per inserire tutti i prodotti -->
INSERT INTO product (title, description, sub_category_id, date, user_id)
VALUES ('Animazione Personalizzata per Video Promozionali',
        'Creazione di animazioni personalizzate per spot pubblicitari, video aziendali e contenuti per i social media. Stili disponibili: 2D, 3D, motion graphics.',
        16, LOCALTIME, 3),

       ('Sviluppo Applicazioni Web Personalizzate',
        'Sviluppo di applicazioni web moderne e scalabili utilizzando tecnologie come Angular, React e Node.js.', 28,
        LOCALTIME, 4),

       ('Ottimizzazione SEO per Siti Web',
        'Servizi di ottimizzazione SEO per migliorare la visibilità del tuo sito sui motori di ricerca.', 38, LOCALTIME,
        4),

       ('Fotografia Professionale di Prodotti',
        'Servizi di fotografia professionale per e-commerce, pubblicità e packaging.', 64, LOCALTIME, 3),

       ('Produzione Audio e Sound Design',
        'Produzione e mixaggio audio professionale per video, podcast e progetti multimediali.', 45, LOCALTIME, 6),

       ('Servizio di Traduzione Italiano-Inglese',
        'Traduzione professionale di documenti, siti web e manuali tecnici.', 20, LOCALTIME, 3),

       ('Illustrazione Personalizzata',
        'Creazione di illustrazioni uniche per libri, riviste o progetti personali.', 16, LOCALTIME, 4),

       ('Consulenza Strategica Aziendale',
        'Supporto nella definizione di strategie di crescita e sviluppo.', 28, LOCALTIME, 6),

       ('Fotografia per Eventi',
        'Servizio fotografico per matrimoni, eventi aziendali e celebrazioni.', 64, LOCALTIME, 8),

       ('Creazione Video Pubblicitari',
        'Produzione di spot pubblicitari professionali per TV e social media.', 45, LOCALTIME, 9),

       ('Scrittura di Contenuti SEO',
        'Creazione di articoli ottimizzati per migliorare il ranking del tuo sito.', 38, LOCALTIME, 10),

       ('Design Logo Professionale',
        'Progettazione di loghi aziendali moderni e accattivanti.', 16, LOCALTIME, 11),

       ('Modellazione 3D per Progetti Architettonici',
        'Creazione di modelli 3D dettagliati per architettura e design.', 16, LOCALTIME, 12),

       ('Consulenza Legale per Start-up',
        'Supporto legale per avviare e gestire la tua start-up.', 28, LOCALTIME, 3),

       ('Editing Video Professionale',
        'Montaggio video per documentari, eventi o video promozionali.', 45, LOCALTIME, 4),

       ('Ottimizzazione Social Media',
        'Gestione e ottimizzazione di campagne social su Facebook e Instagram.', 38, LOCALTIME, 6);

-- Query per inserire tutti i pacchetti di prodotti -->
INSERT INTO product_package (product_id, type, price, description, delivery_time, revisions, email_support,
                             chat_support)
VALUES (1, 'BASIC', 150.0, 'Animazione semplice di 15-30 secondi, ideale per video introduttivi.', 5, 1, true, false),
       (1, 'PREMIUM', 350.0, 'Animazione fino a 60 secondi con grafica avanzata e transizioni fluide.', 10, 2, true,
        true),
       (1, 'DELUXE', 700.0, 'Animazione personalizzata fino a 120 secondi con scenari complessi.', 20, 3, true, true),

       (2, 'BASIC', 500.0, 'Sviluppo di una singola pagina web dinamica con design personalizzato.', 7, 2, true, false),
       (2, 'PREMIUM', 1500.0, 'Applicazione multi-pagina con integrazione API e design responsivo.', 14, 3, true, true),
       (2, 'DELUXE', 3000.0, 'Applicazione web completa con backend personalizzato e database.', 30, 5, true, true),

       (3, 'BASIC', 100.0, 'Analisi base e ottimizzazione di 3 pagine del sito.', 3, 1, true, false),
       (3, 'PREMIUM', 300.0, 'Ottimizzazione completa fino a 10 pagine e audit tecnico.', 7, 2, true, true),
       (3, 'DELUXE', 700.0, 'Strategia SEO avanzata per siti con oltre 20 pagine.', 15, 3, true, true),

       (4, 'BASIC', 100.0, 'Fotografia di 5 prodotti con editing base.', 5, 1, true, false),
       (4, 'PREMIUM', 300.0, 'Fotografia di 15 prodotti con editing avanzato e sfondo personalizzato.', 10, 2, true,
        true),
       (4, 'DELUXE', 600.0, 'Servizio fotografico completo per 30 prodotti con opzioni creative.', 20, 3, true, true),

       (5, 'BASIC', 200.0, 'Produzione di una traccia audio base di 1-2 minuti.', 7, 2, true, false),
       (5, 'PREMIUM', 500.0, 'Produzione avanzata di una traccia di 3-5 minuti con sound design personalizzato.', 14, 3,
        true, true),
       (5, 'DELUXE', 1000.0, 'Composizione audio completa per progetti cinematografici o giochi.', 30, 5, true, true),

       (6, 'BASIC', 50.0, 'Traduzione di 1000 parole con revisione base.', 2, 1, true, false),
       (6, 'PREMIUM', 100.0, 'Traduzione di 3000 parole con revisione avanzata.', 5, 2, true, true),
       (6, 'DELUXE', 200.0, 'Traduzione di 5000 parole con consulenza linguistica.', 7, 3, true, true),

       (7, 'BASIC', 80.0, 'Illustrazione in bianco e nero.', 3, 1, true, false),
       (7, 'PREMIUM', 150.0, 'Illustrazione a colori con 1 revisione.', 7, 2, true, true),
       (7, 'DELUXE', 300.0, 'Illustrazione dettagliata con sfondi complessi.', 10, 3, true, true),

       (8, 'BASIC', 500.0, 'Consulenza strategica di 2 ore.', 3, 1, true, false),
       (8, 'PREMIUM', 1200.0, 'Consulenza strategica con analisi approfondita.', 7, 2, true, true),
       (8, 'DELUXE', 2500.0, 'Consulenza full-time per un mese.', 30, 3, true, true),

       (9, 'BASIC', 300.0, 'Fotografia per un evento di 2 ore.', 3, 1, true, false),
       (9, 'PREMIUM', 800.0, 'Fotografia con post-produzione inclusa.', 7, 2, true, true),
       (9, 'DELUXE', 1500.0, 'Servizio fotografico per un evento intero.', 10, 3, true, true),

       (10, 'BASIC', 1000.0, 'Video pubblicitario base di 30 secondi.', 7, 1, true, false),
       (10, 'PREMIUM', 2500.0, 'Video pubblicitario con animazioni.', 15, 2, true, true),
       (10, 'DELUXE', 5000.0, 'Produzione completa di uno spot professionale.', 30, 3, true, true),

       (11, 'BASIC', 150.0, 'Scrittura di un articolo di 500 parole.', 3, 1, true, false),
       (11, 'PREMIUM', 350.0, 'Scrittura di 3 articoli SEO ottimizzati.', 7, 2, true, true),
       (11, 'DELUXE', 800.0, 'Piano editoriale completo con 10 articoli.', 15, 3, true, true),

       (12, 'BASIC', 100.0, 'Design di un logo semplice.', 3, 1, true, false),
       (12, 'PREMIUM', 300.0, 'Design di un logo con 3 proposte.', 7, 2, true, true),
       (12, 'DELUXE', 600.0, 'Logo aziendale con manuale d uso.', 15, 3, true, true),

       (13, 'BASIC', 400.0, 'Modellazione di un progetto base.', 5, 1, true, false),
       (13, 'PREMIUM', 800.0, 'Modellazione 3D dettagliata.', 10, 2, true, true),
       (13, 'DELUXE', 1500.0, 'Modellazione 3D avanzata con rendering.', 20, 3, true, true),

       (14, 'BASIC', 250.0, 'Consulenza legale di 1 ora.', 3, 1, true, false),
       (14, 'PREMIUM', 600.0, 'Consulenza legale e revisione contratti.', 7, 2, true, true),
       (14, 'DELUXE', 1200.0, 'Assistenza legale completa per start-up.', 15, 3, true, true),

       (15, 'BASIC', 150.0,
        'Montaggio video base per documentari, eventi o video promozionali, con durata fino a 2 minuti.', 5, 1, true,
        false),
       (15, 'PREMIUM', 350.0,
        'Montaggio video avanzato con effetti speciali e transizioni fluide, durata fino a 5 minuti.', 10, 2, true,
        true),
       (15, 'DELUXE', 700.0,
        'Montaggio video personalizzato con animazioni, correzioni colore e mix audio professionale, durata fino a 10 minuti.',
        20, 3, true, true),

       (16, 'BASIC', 120.0, 'Gestione di una campagna su Facebook o Instagram, ottimizzazione post e targeting base.',
        5, 1, true, false),
       (16, 'PREMIUM', 250.0, 'Gestione avanzata delle campagne con report settimanali e analisi approfondite.', 10, 2,
        true, true),
       (16, 'DELUXE', 500.0,
        'Gestione completa di campagne su entrambe le piattaforme con ottimizzazione dei risultati e supporto 24/7.',
        20, 3, true, true);

-- Query per inserire tutti gli attributi dei pacchetti dei prodotti -->
INSERT INTO package_attribute (product_package_id, attribute_key, attribute_value)
VALUES -- Pacchetto 1: Animazione semplice
       (1, 'Durata', '"15-30 secondi"'),
       (1, 'Formato', '"MP4"'),
       (1, 'Stile', '"2D, Motion Graphics"'),
       (1, 'Animazione', '"Semplice, Lineare"'),
       (1, 'Transizioni', '"Base"'),
       (1, 'Revisione', '"1 revisione"'),
       (1, 'Voce fuori campo', '"Non inclusa"'),

-- Pacchetto 2: Animazione Premium
       (2, 'Durata', '"30-60 secondi"'),
       (2, 'Formato', '"MP4, MOV"'),
       (2, 'Stile', '"2D, 3D, Motion Graphics"'),
       (2, 'Animazione', '"Avanzata, Dettagliata"'),
       (2, 'Transizioni', '"Fluide, Professionali"'),
       (2, 'Revisione', '"2 revisioni"'),
       (2, 'Voce fuori campo', '"Opzionale"'),

-- Pacchetto 3: Animazione Deluxe
       (3, 'Durata', '"90-120 secondi"'),
       (3, 'Formato', '"MP4, MOV, AVI"'),
       (3, 'Stile', '"2D, 3D, Motion Graphics avanzato"'),
       (3, 'Animazione', '"Complessiva, Personalizzata"'),
       (3, 'Transizioni', '"Avanzate, Creative"'),
       (3, 'Revisione', '"3 revisioni"'),
       (3, 'Voce fuori campo', '"Opzionale, Inclusa con aggiunta"'),

-- Pacchetto 4: Sviluppo Web Base
       (4, 'Linguaggi supportati', '"HTML, CSS, JavaScript"'),
       (4, 'Hosting incluso', '"Non incluso"'),
       (4, 'Framework', '"Bootstrap"'),
       (4, 'Responsive', '"Sì"'),
       (4, 'SEO', '"Base"'),
       (4, 'Pagine', '"1 pagina"'),

-- Pacchetto 5: Sviluppo Web Premium
       (5, 'Framework', '"Angular, React"'),
       (5, 'Integrazione API', '"Sì"'),
       (5, 'Database', '"MySQL, MongoDB"'),
       (5, 'Responsive', '"Sì"'),
       (5, 'SEO', '"Avanzato"'),
       (5, 'Pagine', '"Fino a 5 pagine"'),

-- Pacchetto 6: Sviluppo Web Deluxe
       (6, 'Tecnologie backend', '"Node.js, Express"'),
       (6, 'Database', '"MySQL, MongoDB"'),
       (6, 'Integrazione API', '"Completa, Personalizzata"'),
       (6, 'Responsive', '"Sì"'),
       (6, 'SEO', '"Avanzato"'),
       (6, 'Sicurezza', '"Alta, Criptazione dei dati"'),
       (6, 'Pagine', '"Fino a 10 pagine"'),

-- Pacchetto 7: Ottimizzazione SEO Base
       (7, 'Numero di pagine', '"3"'),
       (7, 'Report SEO', '"Incluso"'),
       (7, 'Tipo di SEO', '"SEO On-Page"'),
       (7, 'Analisi concorrenti', '"Non inclusa"'),
       (7, 'Parole chiave', '"Fino a 5"'),

-- Pacchetto 8: Ottimizzazione SEO Premium
       (8, 'Numero di pagine', '"Fino a 10"'),
       (8, 'Report SEO', '"Incluso"'),
       (8, 'Tipo di SEO', '"SEO On-Page, SEO Off-Page"'),
       (8, 'Analisi concorrenti', '"Inclusa"'),
       (8, 'Parole chiave', '"Fino a 15"'),

-- Pacchetto 9: Ottimizzazione SEO Deluxe
       (9, 'Numero di pagine', '"Fino a 20"'),
       (9, 'Report SEO', '"Dettagliato, Personalizzato"'),
       (9, 'Tipo di SEO', '"SEO Completo, Auditing"'),
       (9, 'Analisi concorrenti', '"Completa"'),
       (9, 'Parole chiave', '"Fino a 30"'),

-- Pacchetto 10: Fotografia Base
       (10, 'Numero di prodotti', '"5"'),
       (10, 'Tipo di fotografia', '"Prodotti, Base"'),
       (10, 'Editing', '"Base, Senza sfondi"'),
       (10, 'Formato immagini', '"JPG, PNG"'),
       (10, 'Tipo di sfondo', '"Neutro"'),

-- Pacchetto 11: Fotografia Premium
       (11, 'Numero di prodotti', '"15"'),
       (11, 'Tipo di fotografia', '"Prodotti, Avanzata"'),
       (11, 'Editing', '"Avanzato, Sfondo personalizzato"'),
       (11, 'Formato immagini', '"JPG, PNG, TIFF"'),
       (11, 'Tipo di sfondo', '"Personalizzato, Creativo"'),

-- Pacchetto 12: Fotografia Deluxe
       (12, 'Numero di prodotti', '"30"'),
       (12, 'Tipo di fotografia', '"Servizio fotografico completo"'),
       (12, 'Editing', '"Avanzato, Personalizzato"'),
       (12, 'Formato immagini', '"JPG, PNG, TIFF, RAW"'),
       (12, 'Tipo di sfondo', '"Creativo, Scenografico"'),

-- Pacchetto 13: Composizione Audio Base
       (13, 'Durata traccia', '"1-2 minuti"'),
       (13, 'Tipo di composizione', '"Base, senza sound design"'),
       (13, 'Qualità audio', '"MP3 192kbps"'),
       (13, 'Strumenti', '"Standard, MIDI"'),

-- Pacchetto 14: Composizione Audio Premium
       (14, 'Durata traccia', '"3-5 minuti"'),
       (14, 'Tipo di composizione', '"Avanzata, Sound design personalizzato"'),
       (14, 'Qualità audio', '"WAV 24bit"'),
       (14, 'Strumenti', '"Strumenti professionali, MIDI, VST"'),

-- Pacchetto 15: Composizione Audio Deluxe
       (15, 'Durata traccia', '"Fino a 10 minuti"'),
       (15, 'Tipo di composizione', '"Completamente personalizzata, Sound design complesso"'),
       (15, 'Qualità audio', '"WAV 24bit, Mastering professionale"'),
       (15, 'Strumenti', '"Strumenti professionali, Orchestrali, VST, Live Recording"'),

-- Pacchetto 16: Traduzione Base
       (16, 'Parole supportate', '"Fino a 1000"'),
       (16, 'Revisione', '"Base"'),
       (16, 'Tipo di traduzione', '"Generica, Senza glossario"'),

-- Pacchetto 17: Traduzione Premium
       (17, 'Parole supportate', '"Fino a 3000"'),
       (17, 'Revisione', '"Avanzata"'),
       (17, 'Tipo di traduzione', '"Tecnica, Settoriale"'),

-- Pacchetto 18: Traduzione Deluxe
       (18, 'Parole supportate', '"Fino a 5000"'),
       (18, 'Revisione', '"Completa, Consulenza linguistica"'),
       (18, 'Tipo di traduzione', '"Legale, Medica, Settoriale avanzata"'),

-- Pacchetto 19: Illustrazione Base
       (19, 'Tipo di illustrazione', '"Bianco e nero"'),
       (19, 'Dettaglio', '"Base, Senza sfondi complessi"'),
       (19, 'Revisione', '"1 revisione"'),

-- Pacchetto 20: Illustrazione Premium
       (20, 'Tipo di illustrazione', '"A colori"'),
       (20, 'Dettaglio', '"Con sfondi e dettagli"'),
       (20, 'Revisione', '"2 revisioni"'),

-- Pacchetto 21: Illustrazione Deluxe
       (21, 'Tipo di illustrazione', '"Dettagliata, Con sfondi complessi"'),
       (21, 'Revisione', '"3 revisioni"'),

-- Pacchetto 22: Consulenza Strategica Base
       (22, 'Durata', '"2 ore"'),
       (22, 'Tipo di consulenza', '"Base, Strategia aziendale"'),
       (22, 'Analisi', '"Generale"'),

-- Pacchetto 23: Consulenza Strategica Premium
       (23, 'Durata', '"7 ore"'),
       (23, 'Tipo di consulenza', '"Avanzata, Marketing e Business"'),
       (23, 'Analisi', '"Approfondita, SWOT"'),

-- Pacchetto 24: Consulenza Strategica Deluxe
       (24, 'Durata', '"30 giorni"'),
       (24, 'Tipo di consulenza', '"Full-time, Completamente personalizzata"'),
       (24, 'Analisi', '"Complete, Monitoraggio e strategie continuative"'),

       -- Pacchetto 9: Fotografia
       (25, 'Durata', '"2 ore"'),
       (25, 'Tipo di servizio', '"Fotografia per evento"'),
       (25, 'Post-produzione', '"false"'),

       (26, 'Durata', '"2 ore"'),
       (26, 'Tipo di servizio', '"Fotografia con post-produzione"'),
       (26, 'Post-produzione', '"Inclusa"'),

       (27, 'Durata', '"Intero evento"'),
       (27, 'Tipo di servizio', '"Servizio fotografico completo"'),
       (27, 'Post-produzione', '"Inclusa"'),

       -- Pacchetto 10: Video Pubblicitario
       (28, 'Durata', '"30 secondi"'),
       (28, 'Tipo di servizio', '"Video pubblicitario base"'),
       (28, 'Animazioni', '"false"'),

       (29, 'Durata', '"30 secondi"'),
       (29, 'Tipo di servizio', '"Video con animazioni"'),
       (29, 'Animazioni', '"true"'),

       (30, 'Durata', '"Produzione completa"'),
       (30, 'Tipo di servizio', '"Spot professionale"'),
       (30, 'Animazioni', '"true"'),

       -- Pacchetto 11: Scrittura Articoli
       (31, 'Numero di parole', '"500"'),
       (31, 'Tipo di contenuto', '"Articolo SEO"'),
       (31, 'Numero di articoli', '"1"'),

       (32, 'Numero di parole', '"500 per articolo"'),
       (32, 'Tipo di contenuto', '"3 articoli SEO"'),
       (32, 'Numero di articoli', '"3"'),

       (33, 'Numero di articoli', '"10"'),
       (33, 'Tipo di contenuto', '"Piano editoriale completo"'),

       -- Pacchetto 12: Design Logo
       (34, 'Tipo di logo', '"Semplice"'),
       (34, 'Proposte', '"1 proposta"'),
       (34, 'Manuale d\'uso', '"false"'),

       (35, 'Tipo di logo', '"Con 3 proposte"'),
       (35, 'Proposte', '"3"'),
       (35, 'Manuale d\'uso', '"false"'),

       (36, 'Tipo di logo', '"Logo aziendale"'),
       (36, 'Proposte', '"1 proposta"'),
       (36, 'Manuale d\'uso', '"true"'),

       -- Pacchetto 13: Modellazione 3D
       (37, 'Tipo di progetto', '"Base"'),
       (37, 'Tipo di modellazione', '"3D base"'),
       (37, 'Rendering', '"false"'),

       (38, 'Tipo di modellazione', '"3D avanzato"'),
       (38, 'Rendering', '"true"'),

       (39, 'Tipo di progetto', '"Avanzato con rendering"'),
       (39, 'Tipo di modellazione', '"3D avanzato"'),
       (39, 'Rendering', '"true"'),

       -- Pacchetto 14: Consulenza Legale
       (40, 'Durata', '"1 ora"'),
       (40, 'Tipo di consulenza', '"Base"'),
       (40, 'Revisione contratti', '"false"'),

       (41, 'Durata', '"Consulenza e revisione contratti"'),
       (41, 'Tipo di consulenza', '"Avanzata"'),
       (41, 'Revisione contratti', '"true"'),

       (42, 'Durata', '"Assistenza legale"'),
       (42, 'Tipo di consulenza', '"Completamente personalizzata"'),
       (42, 'Revisione contratti', '"true"'),
       -- Pacchetto 15: Montaggio Video
       (43, 'Durata', '"Fino a 2 minuti"'),
       (43, 'Tipo di montaggio', '"Base"'),
       (43, 'Effetti speciali', '"false"'),

       (44, 'Durata', '"Fino a 5 minuti"'),
       (44, 'Tipo di montaggio', '"Avanzato con effetti speciali"'),
       (44, 'Effetti speciali', '"true"'),

       (45, 'Durata', '"Fino a 10 minuti"'),
       (45, 'Tipo di montaggio', '"Personalizzato con animazioni"'),
       (45, 'Effetti speciali', '"true"'),

       (46, 'Piattaforme', '"Facebook, Instagram"'),
       (46, 'Tipo di gestione', '"Base con targeting"'),
       (46, 'Report', '"false"'),

       (47, 'Piattaforme', '"Facebook, Instagram"'),
       (47, 'Tipo di gestione', '"Avanzata con report settimanali"'),
       (47, 'Report', '"true"'),

       (48, 'Piattaforme', '"Facebook, Instagram"'),
       (48, 'Tipo di gestione', '"Completa con ottimizzazione"'),
       (48, 'Report', '"true"'),
       (48, 'Supporto', '"24/7"');

-- Query per inserire tutti i tag
INSERT INTO product_tag (product_id, tag_id)
VALUES (1, (SELECT id FROM tag WHERE name = 'Animazione 2D')),
       (1, (SELECT id FROM tag WHERE name = 'Animazione 3D')),
       (1, (SELECT id FROM tag WHERE name = 'Motion graphics')),

       (2, (SELECT id FROM tag WHERE name = 'Full stack')),
       (2, (SELECT id FROM tag WHERE name = 'Web app')),
       (2, (SELECT id FROM tag WHERE name = 'API integration')),

       (3, (SELECT id FROM tag WHERE name = 'SEO')),
       (3, (SELECT id FROM tag WHERE name = 'SEO tecnico')),
       (3, (SELECT id FROM tag WHERE name = 'Analisi della concorrenza')),

       (4, (SELECT id FROM tag WHERE name = 'Fotografia prodotti')),
       (4, (SELECT id FROM tag WHERE name = 'Fotografia e-commerce')),
       (4, (SELECT id FROM tag WHERE name = 'Editing fotografico avanzato')),

       (5, (SELECT id FROM tag WHERE name = 'Sound design')),
       (5, (SELECT id FROM tag WHERE name = 'Mixaggio')),
       (5, (SELECT id FROM tag WHERE name = 'Produzione musicale'));

-- Query per inserire tutte le foto dei prodotti
INSERT INTO product_photo (product_id, url_product_photo)
VALUES (13, 'products/Product_WithUserId_12/20240510_Modellazione_3D_0.jpg'),
       (13, 'products/Product_WithUserId_12/edificius-progettazione-architettonica-video-anteprima.jpg'),
       (13, 'products/Product_WithUserId_12/int-mod.jpg'),
       (13, 'products/Product_WithUserId_12/int_v1_ext_side_day_1024_ok.jpg'),
       (13, 'products/Product_WithUserId_12/quattro-motivi-per-studiare-modellazione-3D-750x450.png'),
       (13, 'products/Product_WithUserId_12/render-villa.png'),
       (13, 'products/Product_WithUserId_12/skechtup-modellazione-3d-architettura-interior-design-certificato.jpg'),
       (2, 'products/Product_WithUserId_4/66e219a0b475085e390d908f_AD_4nXehY6LRgeCOjEUfj26K8msS.png'),
       (2, 'products/Product_WithUserId_4/freepik__upload__25619.png'),
       (2, 'products/Product_WithUserId_4/freepik__upload__58619.png'),
       (2, 'products/Product_WithUserId_4/freepik__upload__77316.png'),
       (2, 'products/Product_WithUserId_4/Screen-Shot-2019-04-14-at-15.43.52-768x482.png'),
       (2, 'products/Product_WithUserId_4/trendy-wears-ecommerce-website-design-by-dientweb.net-preview.jpg'),
       (3, 'products/Product_WithUserId_4/Ottimizzare-le-immagini-SEO.jpg'),
       (3, 'products/Product_WithUserId_4/2091-gsc.png'),
       (3, 'products/Product_WithUserId_4/1692733095993.png'),
       (3, 'products/Product_WithUserId_4/SEO.png'),
       (3, 'products/Product_WithUserId_4/seo-strategy-5-step-framework-899x380.jpg'),
       (3, 'products/Product_WithUserId_4/SEOTips_Blog_07012023-1.png'),
       (3, 'products/Product_WithUserId_4/seo-tips-and-tricks.jpg'),
       (16, 'products/Product_WithUserId_6/1679245060514.png'),
       (16, 'products/Product_WithUserId_6/1686136363537.png'),
       (16, 'products/Product_WithUserId_6/AdobeStock_115082100-scaled.jpeg'),
       (16, 'products/Product_WithUserId_6/course_1663052587.jpg'),
       (16, 'products/Product_WithUserId_6/social.jpg'),
       (16, 'products/Product_WithUserId_6/social-media-marketing-la-gi.jpg'),
       (16, 'products/Product_WithUserId_6/Social-Media-marketing-strategy-The-Go-To-Guy.jpg'),
       (16, 'products/Product_WithUserId_6/social-media-market.jpg'),
       (16, 'products/Product_WithUserId_6/The-Landscape-of-Social-Media-Marketing.png'),
       (8, 'products/Product_WithUserId_6/andrewsax-studio-consulenza-aziendale.jpg'),
       (8, 'products/Product_WithUserId_6/CeR-Strategia-aziendale_Anteprima1.jpg'),
       (8, 'products/Product_WithUserId_6/consulenza-aziendale.jpg'),
       (8, 'products/Product_WithUserId_6/Consulenza-aziendale-1-fb.jpg'),
       (8, 'products/Product_WithUserId_6/consulenza-aziendale-cosa-facciamo-per-voi.jpg'),
       (8, 'products/Product_WithUserId_6/consulenza-aziendale-more-solutions.jpg'),
       (8, 'products/Product_WithUserId_6/gestione-cespiti-aziendali-con-rfid.jpg'),
       (8, 'products/Product_WithUserId_6/la_consulenza_aziendale.jpg'),
       (5, 'products/Product_WithUserId_6/1d9e0c91-8963-4855-87af-f1a2e56d3020.jpeg'),
       (5, 'products/Product_WithUserId_6/Audio_Studio7_1-Large.jpeg'),
       (5, 'products/Product_WithUserId_6/maxresdefault.jpg'),
       (5, 'products/Product_WithUserId_6/migliori-programmi-daw-software-produzione-musicale.jpg'),
       (5, 'products/Product_WithUserId_6/post-produzione-audio-2.jpg'),
       (5, 'products/Product_WithUserId_6/Untitled-design-1.jpg'),
       (5,
        'products/Product_WithUserId_6/What-Does-a-Sound-Designer-Do-Sound-Designer-Role-Sound-Designer-Duties-Explained-scaled.jpg'),
       (4, 'products/Product_WithUserId_3/STYCM.jpg'),
       (4, 'products/Product_WithUserId_3/studio-concept-trends-shots-agenzia-naj-oleari-still-life-1.jpg'),
       (4, 'products/Product_WithUserId_3/still-life-borse-bags-firenze-fashion004.jpg'),
       (4, 'products/Product_WithUserId_3/precio-fotografia-producto-ecommerce.jpg'),
       (4, 'products/Product_WithUserId_3/fotografare-prodotti-per-e-commerce-1024x683.jpg'),
       (4, 'products/Product_WithUserId_3/fotografare-oggetti-riflettenti-1024x683.jpg'),
       (4, 'products/Product_WithUserId_3/2022_Trilab_Banner Brand_Categoria_IMG_8108_14mar22_Anticaduta_1168x840.jpg'),
       (4, 'products/Product_WithUserId_3/171.jpg'),
       (6, 'products/Product_WithUserId_3/ita-eng.jpg'),
       (6, 'products/Product_WithUserId_3/language-translation-services_223.jpg'),
       (6,
        'products/Product_WithUserId_3/Traduzione-siti-italiano-inglese-servizio-web-copywriting-per-aziende@2x.jpg'),
       (6, 'products/Product_WithUserId_3/translations-1-810x500-4f75aa.jpg'),
       (6, 'products/Product_WithUserId_3/Translation-Services.jpg'),
       (6, 'products/Product_WithUserId_3/translation-services.png'),
       (6, 'products/Product_WithUserId_3/Which-Industries-need-translation-services.jpg'),
       (14, 'products/Product_WithUserId_3/consulenza-legale-online.jpg'),
       (14, 'products/Product_WithUserId_3/keplera.png'),
       (14, 'products/Product_WithUserId_3/post-in_avvocato-startup-1024x535.png'),
       (14, 'products/Product_WithUserId_3/slide-1.jpg'),
       (14, 'products/Product_WithUserId_3/start-up-innovative-agevolazioni-fiscali-2022.jpg'),
       (1, 'products/Product_WithUserId_3/servizi_produzione_spot_televisivi_video_promozionali_service.jpg'),
       (1, 'products/Product_WithUserId_3/video-marketing.jpg'),
       (1, 'products/Product_WithUserId_3/videopromo_aziende_spot.jpg'),
       (1, 'products/Product_WithUserId_3/video-promo-800x449.png'),
       (1, 'products/Product_WithUserId_3/video-promozionali-845x321.jpg'),
       (7, 'products/Product_WithUserId_4/001-understand-yourself-large-opt.png'),
       (7, 'products/Product_WithUserId_4/164251.jpg'),
       (7, 'products/Product_WithUserId_4/cover.jpgg'),
       (7, 'products/Product_WithUserId_4/image-88-e1692385167766.png'),
       (7, 'products/Product_WithUserId_4/llustration-trends-2650x1439.jpg'),
       (7, 'products/Product_WithUserId_4/sddefault.jpg'),
       (7, 'products/Product_WithUserId_4/what_is_illustration_example_illustrator.jpg'),
       (15, 'products/Product_WithUserId_4/64dc1ed3a926ddaf9d6eecab_importance-of-editing.jpg'),
       (15, 'products/Product_WithUserId_4/Best-free-video-editing-software-AU-Capterra-Header.png'),
       (15, 'products/Product_WithUserId_4/best-free-video-editing-software-pc.jpg'),
       (15, 'products/Product_WithUserId_4/Editing-Video.jpg'),
       (15, 'products/Product_WithUserId_4/premiere.jpg'),
       (15, 'products/Product_WithUserId_4/repaper_blogpost_44_background.jpg'),
       (9, 'products/Product_WithUserId_8/02-eventi-1.jpg'),
       (9, 'products/Product_WithUserId_8/come-scegliere-il-fotografo-per-eventi.png'),
       (9, 'products/Product_WithUserId_8/Cosa-considerare-prima-di-scegliere-una-location-per-eventi-in-Toscana.png'),
       (9, 'products/Product_WithUserId_8/Ecco-la-tua-location-per-eventi-a-Roma.jpg'),
       (9, 'products/Product_WithUserId_8/fairy-lights.jpg'),
       (9, 'products/Product_WithUserId_8/Foto-e-video-per-eventi-Studio-Fotografico-Righi-1.jpg'),
       (9, 'products/Product_WithUserId_8/fotografo-per-eventi-2.jpg'),
       (9, 'products/Product_WithUserId_8/location-per-eventi.jpg'),
       (10, 'products/Product_WithUserId_9/banner-right-pic.png'),
       (10, 'products/Product_WithUserId_9/commercial-maker-og-image_it.png'),
       (10, 'products/Product_WithUserId_9/csm_spot-coca-cola-europei-2020_016a408bf5.jpg'),
       (10, 'products/Product_WithUserId_9/improve-visual-effect.png'),
       (10, 'products/Product_WithUserId_9/spot-tv.jpg'),
       (10, 'products/Product_WithUserId_9/video.jpg'),
       (11, 'products/Product_WithUserId_10/pubblicazionecontenutiseofriendly.png'),
       (11, 'products/Product_WithUserId_10/scrittura-seo-oriented.jpg'),
       (11, 'products/Product_WithUserId_10/Consigli-di-scrittura-per-titoli-SEO_Copy42.jpeg'),
       (11, 'products/Product_WithUserId_10/6398b40f7f278d0ccd8739db_the big-idea-seo-content-writing-checklist.png'),
       (11, 'products/Product_WithUserId_10/6265dd93776abba53474a32c_best-tools-for-seo-content-writing.jpg'),
       (12, 'products/Product_WithUserId_11/5e28d92607cff5aae69f8360_Aqua-Babies-Logo-Redesign.jpg'),
       (12, 'products/Product_WithUserId_11/043c0098429807.5edbf2473c3bd.jpg'),
       (12, 'products/Product_WithUserId_11/1626186765990.jpg'),
       (12, 'products/Product_WithUserId_11/do-professional-graphic-design.jpg'),
       (12, 'products/Product_WithUserId_11/Logo-Wall-Collection-of-logos-designed-in-london-by-jm-graphic-design.jpg'),
       (12, 'products/Product_WithUserId_11/maxresdefault.jpg');

-- Query per inserire tutte le aste -->
INSERT INTO auction (title, description_service, macro_category_id, sub_category_id, delivery_date, start_date,
                     end_date, owner_id, status)
VALUES ('Creazione Loghi Aziendali', 'Cercasi designer per la creazione di un logo aziendale professionale e unico.', 1,
        1, 10, '2024-12-8T09:00:00', '2025-02-15T18:00:00', 7, 'OPEN'),

       ('Progettazione Sito Web',
        'Cerco esperto in web design per sviluppare un sito aziendale responsive e moderno.',
        1, 3, 30, '2024-12-3T10:00:00', '2025-02-12T12:00:00', 3, 'OPEN'),

       ('Animazioni Video Promozionali',
        'Richiesto supporto per creare animazioni video per promuovere un prodotto tecnologico.',
        4, 10, 30, '2024-12-22T15:00:00', '2025-03-01T14:00:00', 5, 'OPEN'),

       ('Ottimizzazione SEO per Blog',
        'Cerco consulente SEO per migliorare il posizionamento di un blog personale.',
        3, 13, 25, '2024-12-29T08:00:00', '2025-02-27T18:00:00', 4, 'OPEN'),

       ('Progettazione App E-commerce',
        'Necessito di uno sviluppatore per progettare un app di e-commerce intuitiva e scalabile.',
        2, 8, 40, '2024-12-9T09:00:00', '2025-02-25T15:00:00', 6, 'OPEN'),

       ('Restyling Identità Visiva',
        'Cercasi designer per aggiornare l identità visiva di un brand esistente.',
        1, 16, 20, '2024-12-8T10:00:00', '2025-02-13T12:00:00', 3, 'OPEN'),

       ('Produzione Jingle Pubblicitario',
        'Richiesto un compositore per creare un jingle pubblicitario accattivante.',
        5, 4, 15, '2025-02-13T14:00:00', '2025-02-19T10:00:00', 6, 'PENDING'),

       ('Fotografia Prodotti di Lusso',
        'Cerco fotografo esperto per scatti professionali di prodotti di lusso.',
        9, 1, 25, '2024-12-05T11:00:00', '2024-12-23T16:00:00', 7, 'OPEN'),

       ('Sviluppo Applicazione VR',
        'Necessito di un programmatore per sviluppare un applicazione VR interattiva.',
        2, 11, 45, '2024-08-04T09:00:00', '2025-03-15T18:00:00', 5, 'OPEN'),

       ('Realizzazione Brochure Aziendale',
        'Cerco un grafico per progettare una brochure aziendale moderna e informativa.',
        1, 11, 348, '2023-12-29T13:00:00', '2024-01-25T14:00:00', 5, 'OPEN'),

       ('Creazione Logo Professionale',
        'Richiesto un designer per creare un logo professionale per un brand emergente.',
        1, 1, 300, '2024-11-18T10:00:00', '2025-01-18T10:00:00', 16, 'OPEN'),

       ('Sviluppo Applicazione E-learning',
        'Necessario uno sviluppatore per creare un app educativa innovativa.',
        2, 7, 60, '2024-08-19T09:00:00', '2025-02-17T18:00:00', 3, 'OPEN'),

       ('Ottimizzazione SEO per E-commerce',
        'Cerco consulente esperto per migliorare il ranking di un e-commerce.',
        3, 13, 40, '2024-10-20T11:00:00', '2025-01-29T14:00:00', 4, 'OPEN'),

       ('Animazione Video Promozionale',
        'Richiesta animazione per promuovere un nuovo prodotto tecnologico.',
        4, 9, 62, '2024-09-21T08:00:00', '2025-02-21T12:00:00', 5, 'OPEN'),

       ('Produzione Musica per Video',
        'Cercasi musicista per creare una traccia per video aziendale.',
        5, 10, 20, '2024-12-13T14:00:00', '2025-01-11T10:00:00', 6, 'OPEN'),

       ('Progettazione Brochure',
        'Cerco grafico per realizzare una brochure professionale per un evento.',
        1, 11, 15, '2024-12-23T10:00:00', '2025-01-07T12:00:00', 7, 'PENDING'),

       ('Sviluppo Software Gestionale',
        'Necessario sviluppo di un software gestionale per piccole imprese.',
        2, 14, 90, '2024-12-12T09:00:00', '2025-03-24T18:00:00', 8, 'OPEN'),

       ('Fotografia per Campagna Pubblicitaria',
        'Richiesto un fotografo per realizzare immagini di alta qualità.',
        9, 10, 30, '2024-12-11T11:00:00', '2025-01-25T16:00:00', 9, 'OPEN'),

       ('Voice Over per Spot Pubblicitario',
        'Cerco voce narrante professionale per spot promozionale.',
        5, 4, 10, '2024-12-26T13:00:00', '2025-01-05T15:00:00', 10, 'PENDING'),

       ('Restyling Sito Web',
        'Cercasi esperto per restyling di un sito web aziendale.',
        1, 3, 45, '2024-07-27T09:00:00', '2025-02-11T12:00:00', 11, 'OPEN'),

       ('Campagna Marketing Digitale',
        'Necessario esperto per ideare e gestire una campagna di marketing digitale.',
        3, 6, 45, '2025-02-16T10:00:00', '2025-03-11T14:00:00', 12, 'PENDING'),

       ('Editing Video per YouTube',
        'Cerco editor per montaggio video destinati a un canale YouTube.',
        4, 2, 20, '2025-02-04T02:37:00', '2025-03-18T16:00:00', 13, 'PENDING'),

       ('Composizione Colonna Sonora',
        'Richiesto compositore per creare una colonna sonora personalizzata.',
        5, 9, 60, '2024-12-30T11:00:00', '2025-01-18T16:00:00', 14, 'PENDING'),

       ('Consulenza Strategica Aziendale',
        'Cerco consulente per sviluppare una strategia aziendale innovativa.',
        8, 1, 94, '2024-12-04T04:37:00', '2025-03-31T15:00:00', 15, 'OPEN'),

       ('Fotografia per Social Media',
        'Cerco fotografo per contenuti social di alta qualità.',
        9, 10, 25, '2024-12-04T04:37:00', '2025-02-06T18:00:00', 16, 'OPEN'),

       ('Creazione Banner Pubblicitari',
        'Necessario designer per creare banner pubblicitari accattivanti.',
        1, 14, 30, '2024-12-02T19:37:00', '2025-02-02T16:00:00', 17, 'OPEN'),

       ('Consulenza IT per Startup',
        'Cerco esperto IT per supporto tecnico per una startup.',
        8, 2, 45, '2024-12-03T09:37:00', '2025-02-17T18:00:00', 13, 'OPEN'),

       ('Produzione Podcast',
        'Richiesta assistenza per produzione e editing di un podcast.',
        5, 3, 45, '2024-12-01T09:37:00', '2025-02-19T16:00:00', 14, 'OPEN'),

       ('Gestione Campagne PPC',
        'Cerco esperto per gestire campagne PPC su Google Ads.',
        3, 4, 70, '2025-01-05T10:00:00', '2025-02-15T15:00:00', 17, 'PENDING'),

       ('Illustrazione Personalizzata',
        'Cercasi illustratore per creare un design su misura.',
        1, 9, 25, '2024-11-06T08:00:00', '2025-01-31T12:00:00', 10, 'OPEN'),

       ('Lezioni di Musica Online',
        'Cerco insegnante per lezioni di musica online personalizzate.',
        5, 7, 30, '2025-02-06T17:30:00', '2025-02-6T18:00:00', 11, 'PENDING'),

       ('Realizzazione Video Esplicativi',
        'Richiesto esperto per creare video esplicativi per un prodotto.',
        4, 8, 54, '2024-12-08T11:00:00', '2025-03-08T16:00:00', 15, 'OPEN'),

       ('Produzione Materiale Promozionale',
        'Cerco grafico per creare materiale promozionale accattivante.',
        1, 16, 23, '2024-12-06T12:00:00', '2025-01-26T12:45:00', 4, 'CLOSED'),

       ('Creazione Banner Pubblicitari',
        'Necessario designer per creare banner pubblicitari accattivanti.',
        1, 14, 30, '2024-12-02T19:37:00', '2025-01-26T16:00:00', 4, 'CLOSED'),

       ('Consulenza IT per Startup',
        'Cerco esperto IT per supporto tecnico per una startup.',
        8, 2, 45, '2024-12-03T09:37:00', '2025-01-26T18:00:00', 4, 'CLOSED'),

       ('Produzione Podcast',
        'Richiesta assistenza per produzione e editing di un podcast.',
        5, 3, 45, '2024-12-01T09:37:00', '2025-01-26T16:00:00', 4, 'CLOSED'),

       ('Gestione Campagne PPC',
        'Cerco esperto per gestire campagne PPC su Google Ads.',
        3, 4, 70, '2024-12-05T10:00:00', '2025-01-26T15:00:00', 4, 'CLOSED'),

       ('Illustrazione Personalizzata',
        'Cercasi illustratore per creare un design su misura.',
        1, 9, 25, '2024-11-06T08:00:00', '2025-01-31T12:00:00', 10, 'OPEN'),

       ('Consulenza Marketing per E-commerce',
        'Richiesta consulenza per migliorare le vendite di un e-commerce.',
        8, 3, 12, '2025-01-10T09:00:00', '2025-03-10T15:00:00', 15, 'PENDING');

-- Query per inserire tutte le recensioni -->
INSERT INTO review (comment, date, rating_communication, rating_cost, rating_quality, rating_timeliness, total_rating,
                    product_id, user_id)
VALUES ('Il lavoro è stato svolto in modo impeccabile e non potrei essere più soddisfatto del risultato finale. Ogni aspetto del progetto è stato gestito con attenzione e professionalità, rispettando i tempi previsti e le mie esigenze. La qualità del lavoro è decisamente superiore alle mie aspettative, e posso vedere chiaramente l''impegno che è stato messo in ogni fase. Sono davvero felice di aver scelto questo servizio, e sicuramente lo consiglierò a chiunque stia cercando un lavoro di qualità, senza compromessi.',
        '2024-07-07', 5, 5, 5, 5, 5, 2, 10),
       ('Ho avuto un''esperienza davvero positiva con questo servizio, che ha soddisfatto pienamente le mie aspettative in termini di qualità e professionalità. Il team ha fornito un lavoro eccellente, con una cura nei dettagli che ha reso il risultato finale davvero soddisfacente. Tuttavia, devo ammettere che il prezzo è un po'' più alto rispetto ad altre opzioni sul mercato, anche se credo che la qualità giustifichi il costo aggiuntivo. Nonostante ciò, sono molto contento della scelta fatta e posso affermare che il valore ricevuto è assolutamente in linea con il prezzo pagato.',
        '2024-11-16', 5, 4, 5, 5, 4.75,
        2, 3),
       ('Ho apprezzato molto la puntualità e la qualità del servizio, che sono state davvero superiori alle mie aspettative. Il lavoro è stato eseguito con grande professionalità e precisione. Tuttavia, uno degli aspetti che avrei voluto vedere migliorato è la possibilità di avere più opzioni per la personalizzazione. Avrei gradito maggiore libertà per adattare il risultato alle mie esigenze specifiche. Nonostante questo, sono rimasto soddisfatto del risultato finale e posso comunque raccomandare il servizio.',
        '2024-12-28', 4, 4, 4, 5,
        4.25, 3, 3),
       ('Ho apprezzato molto la puntualità e la qualità del servizio, che sono state davvero superiori alle mie aspettative. Il lavoro è stato eseguito con grande professionalità e precisione. Tuttavia, uno degli aspetti che avrei voluto vedere migliorato è la possibilità di avere più opzioni per la personalizzazione. Avrei gradito maggiore libertà per adattare il risultato alle mie esigenze specifiche. Nonostante questo, sono rimasto soddisfatto del risultato finale e posso comunque raccomandare il servizio.',
        '2024-09-05', 4, 3, 3, 4, 3.5, 4, 6),
       ('Sono estremamente soddisfatto del servizio che ho ricevuto. Mi ha davvero aiutato molto nella gestione del mio sito, offrendo soluzioni pratiche e veloci. Il team è stato disponibile e pronto a rispondere a ogni mia domanda, e il lavoro è stato svolto in modo efficiente. Consiglio vivamente questo servizio a chiunque abbia bisogno di un supporto serio e competente nella gestione del proprio sito web. Sono sicuro che continuerò a collaborare con loro anche in futuro.',
        '2024-06-15', 5, 4, 5, 5, 4.75, 5,
        7),
       ('Sono rimasto molto soddisfatto del servizio ricevuto, sia per quanto riguarda la qualità che per i tempi di consegna. Ogni fase del processo è stata gestita con attenzione, rispettando perfettamente le tempistiche stabilite. Il risultato finale è stato eccellente, e sono davvero contento di aver scelto questa opzione. Il lavoro è stato svolto in maniera impeccabile, e il team ha saputo rispondere rapidamente a tutte le mie richieste. Non posso che esprimere un giudizio estremamente positivo',
        '2024-03-08', 5, 5, 5, 5, 5, 6, 8),
       ('Il servizio che ho ricevuto è stato buono, ma ci sono stati alcuni aspetti che mi hanno lasciato un po'' perplesso. In particolare, ho dovuto aspettare più a lungo di quanto mi aspettassi prima di ricevere il risultato finale. Sebbene la qualità sia stata accettabile, i tempi di consegna hanno influito negativamente sulla mia esperienza complessiva. Sarebbe stato più soddisfacente se fossero stati più rapidi nel completare il lavoro. Tuttavia, la qualità del servizio era comunque adeguata.',
        '2024-04-13', 4, 3, 4, 3, 3.5,
        7, 9),
       ('Il lavoro che mi è stato fornito è stato professionale, ma sinceramente mi aspettavo qualcosa di più, considerando il prezzo che ho pagato. Sebbene il team abbia svolto un buon lavoro, il costo mi sembra un po'' troppo alto rispetto al risultato ottenuto. Non voglio sminuire la qualità del lavoro, ma ritengo che ci siano altre opzioni più competitive in termini di prezzo. In generale, il servizio è stato valido, ma il rapporto qualità/prezzo potrebbe essere migliorato.',
        '2024-10-30', 4, 3, 4,
        4, 3.75, 8, 10),
       ('Ottima qualità e puntualità, ma il supporto clienti non è stato all\'altezza delle aspettative.', '2024-08-02',
        3, 4, 5, 4, 4, 9, 11),
       ('Pienamente soddisfatto del servizio, l\'animazione è venuta proprio come la volevo.', '2024-05-18', 5, 4, 5, 5,
        4.75, 10, 12),
       ('Molto buono il lavoro, ma il processo di comunicazione potrebbe essere più veloce.', '2024-08-06', 3, 3, 5, 4,
        3.75, 11, 13),
       ('Soddisfatto della qualità del lavoro, ma il costo è un po\' troppo alto.', '2024-11-21', 4, 3, 4, 4, 3.75, 12,
        14),
       ('Ho ricevuto esattamente quello che volevo, molto professionale.', '2024-01-11', 5, 5, 5, 5, 5, 13, 15),
       ('Servizio tempestivo, ma avrei preferito una comunicazione più chiara prima della consegna.', '2024-10-07', 4,
        3, 4, 3, 3.5, 14, 16),
       ('Buon lavoro, ma la qualità del materiale potrebbe essere migliorata.', '2024-11-24', 4, 3, 3, 4, 3.5, 15, 17),
       ('Molto professionale, la consegna è avvenuta nei tempi promessi, ma il costo è elevato.', '2024-01-21', 4, 2, 5,
        5, 4, 16, 7),
       ('Il prodotto finale è ottimo, ma i tempi di consegna erano un po\' lunghi.', '2024-06-13', 4, 3, 5, 3, 3.75, 16,
        14),
       ('Molto soddisfatta, ho ottenuto proprio quello che mi aspettavo!', '2025-01-08', 5, 4, 5, 5, 4.75, 4, 4),
       ('Il lavoro è stato eseguito bene, ma la qualità delle foto potrebbe essere migliorata.', '2024-03-15', 3, 4, 3,
        4, 3.5, 2, 11),
       ('Il servizio è stato eccellente, ma non sono del tutto soddisfatto dei tempi di consegna.', '2024-02-07', 4, 3,
        5, 2, 3.5, 3, 7),
       ('La qualità è ottima, ma il prezzo è un po\' troppo alto per quello che ho ricevuto.', '2024-02-12', 4, 3, 4, 4,
        3.75, 4, 9),
       ('Un servizio di qualità, ma la comunicazione ha bisogno di migliorare.', '2024-05-25', 1, 3, 5, 4, 3.25, 5, 15),
       ('Soddisfatto al 100%, consiglio vivamente questo servizio!', '2024-08-18', 5, 5, 5, 5, 5, 6, 16),
       ('Servizio molto buono, ma il supporto potrebbe essere migliorato.', '2025-01-08', 4, 3, 5, 4, 4, 7, 16),
       ('Molto soddisfatto del servizio, ma avrei preferito più personalizzazione nelle opzioni.', '2025-01-07', 4, 3,
        4, 5, 4, 8, 12),
       ('Servizio davvero professionale, ma un po\' più caro rispetto ad altri.', '2025-01-06', 4, 2, 5, 5, 4, 9, 11),
       ('Un ottimo lavoro, ma la qualità audio non era come me l\'aspettavo.', '2025-01-05', 3, 3, 3, 4, 3.25, 10, 12),
       ('Servizio fantastico, ma il costo è leggermente superiore alla media.', '2025-01-04', 5, 4, 5, 5, 4.75, 11, 13),
       ('La qualità è buona, ma la comunicazione è stata un po\' lenta.', '2025-01-03', 4, 3, 4, 3, 3.5, 12, 14),
       ('Il lavoro è stato svolto in modo impeccabile, con una cura dei dettagli che mi ha colpito fin da subito. Il team ha lavorato con molta dedizione e precisione, riuscendo a rispettare le mie aspettative in ogni fase del progetto. La qualità finale è stata eccellente, oltre le mie aspettative iniziali, e sono davvero soddisfatta del risultato finale. Non solo il servizio è stato professionale, ma la disponibilità e l\'approccio al cliente sono stati esemplari. Mi sento di raccomandare questo servizio a chiunque voglia un lavoro ben fatto, senza compromessi.',
        '2025-01-02', 5, 5, 5, 5, 5, 6, 13),

       ('Il servizio ricevuto è stato molto buono, la qualità del lavoro è elevata e il team ha rispettato le tempistiche in modo impeccabile. Tuttavia, uno degli aspetti che mi ha lasciato un po\' perplesso è stato il costo, che è risultato più alto rispetto ad altre offerte simili. Anche se il prezzo è giustificato dalla qualità del lavoro, credo che potrebbe essere un po\' più competitivo. Nel complesso sono comunque soddisfatto del risultato, ma sicuramente prenderò in considerazione anche altre opzioni in futuro se il costo sarà un fattore decisivo.',
        '2025-01-01', 5, 4, 5, 5, 4.75, 2, 15),

       ('Il servizio è stato discreto, ma non eccezionale. Da un lato, la puntualità è stata rispettata e la qualità generale del lavoro è stata buona. Tuttavia, mi aspettavo un maggiore livello di personalizzazione nelle opzioni disponibili. Alcuni dettagli che avrei voluto modificare non sono stati presi in considerazione, e questo ha limitato la mia soddisfazione complessiva. Penso che con più opzioni di personalizzazione, il servizio avrebbe raggiunto il massimo della qualità. Nonostante ciò, il team ha lavorato in modo professionale e rispettato le tempistiche.',
        '2024-10-05', 4, 4, 4, 5, 4.25, 3, 5),

       ('Sfortunatamente, il servizio non ha soddisfatto completamente le mie aspettative. Sebbene la puntualità fosse garantita, la qualità del lavoro finale non era quella che mi aspettavo. Alcuni aspetti del prodotto finale non erano rifiniti come speravo, e la qualità generale non era all\'altezza del prezzo che ho pagato. Il team è stato cortese e professionale, ma purtroppo il risultato finale non è stato all\'altezza delle aspettative. Avrei voluto un maggiore focus sui dettagli e una maggiore attenzione al prodotto finale.',
        '2024-12-10', 2, 3, 2, 3, 2.5, 4, 13),

       ('Il servizio che ho ricevuto è stato generalmente buono, ma non privo di problemi. Da un lato, il lavoro è stato fatto con competenza e il risultato finale è stato accettabile. Tuttavia, i tempi di consegna sono stati un po\' più lunghi di quanto promesso, il che ha creato un po\' di frustrazione. La qualità del prodotto finale è stata buona, ma non straordinaria, e ho riscontrato alcuni piccoli difetti che avrei preferito evitare. Anche la comunicazione, seppur cortese, avrebbe potuto essere un po\' più tempestiva e chiara. Nonostante questi problemi, sono rimasto soddisfatto nel complesso.',
        '2024-12-10', 4, 3, 5, 4, 4, 7, 8),

       ('Il servizio è stato buono, ma non posso fare a meno di notare che la comunicazione è stata un po\' troppo lenta. Il team è stato molto professionale nel rispondere alle mie richieste, ma avrei preferito una maggiore celerità nelle risposte, soprattutto per quanto riguarda la definizione dei dettagli del progetto. La qualità finale è stata soddisfacente, ma non mi ha impressionato particolarmente. Mi aspettavo un risultato un po\' più brillante, considerando le promesse fatte all\'inizio. Penso che ci sia ancora spazio per migliorare, soprattutto nel rendere il processo più fluido e tempestivo.',
        '2024-03-22', 3, 3, 5, 4, 3.75, 11, 13),

       ('Sono rimasto piacevolmente sorpreso dal servizio che ho ricevuto. La qualità del lavoro finale era davvero alta, e il team ha fatto un lavoro eccellente nel soddisfare le mie richieste. La comunicazione, tuttavia, non è stata perfetta: ci sono stati alcuni momenti in cui non ho ricevuto risposte tempestive alle mie domande, e questo ha creato un po\' di frustrazione. Nonostante ciò, il risultato finale è stato davvero soddisfacente, e sono felice di aver scelto questo servizio. Un po\' più di celerità nella comunicazione e avrei dato il massimo dei voti!',
        '2024-03-22', 3, 2, 5, 3, 3.25, 7, 5),

       ('Il prodotto finale è stato nella norma, ma devo ammettere che mi aspettavo qualcosa di più. Il servizio è stato puntuale e il team ha completato il lavoro nei tempi stabiliti, ma la qualità del materiale utilizzato non è stata eccezionale. Inoltre, mi ha un po\' deluso la poca disponibilità a discutere modifiche personalizzate prima della consegna finale. Sebbene il lavoro fosse corretto, non posso dire di essere completamente soddisfatto. Mi sarei aspettato una maggiore attenzione ai dettagli e opzioni di personalizzazione più ampie. Il servizio è comunque buono, ma ci sono dei margini di miglioramento.',
        '2025-01-02', 4, 3, 4, 4, 3.75, 4, 10),

       ('Sono stato completamente soddisfatto del servizio che ho ricevuto. Il team ha fatto un lavoro straordinario, rispettando tutte le richieste e consegnando un prodotto finale di qualità eccezionale. Ogni fase del processo è stata gestita con professionalità e attenzione ai dettagli. La comunicazione è stata perfetta, sempre pronta e chiara. Inoltre, il lavoro è stato completato in tempo, il che è stato un grande vantaggio. In definitiva, consiglio vivamente questo servizio a chiunque voglia un lavoro ben fatto e senza stress. Sicuramente tornerò per altri progetti!',
        '2024-07-02', 5, 5, 5, 5, 5, 13, 15),

       ('Il servizio è stato buono, ma ho trovato che il costo fosse un po\' troppo alto rispetto a quello che ho ricevuto. La qualità del prodotto finale era soddisfacente, ma non ha superato le mie aspettative. La comunicazione è stata discreta, ma non sempre tempestiva, il che ha causato qualche inconveniente. Mi sarebbe piaciuto un maggiore livello di interazione prima della consegna, per evitare malintesi su alcuni dettagli. Alla fine, sono soddisfatto, ma credo che il prezzo possa essere considerato un po\' elevato rispetto al servizio offerto.',
        '2024-10-01', 4, 2, 3, 4, 3.25, 5, 16),

       ('Sono rimasto molto soddisfatto del lavoro che è stato fatto, ma devo segnalare che la comunicazione iniziale avrebbe potuto essere migliore. Non sempre sono riuscito a ottenere risposte rapide alle mie domande, e questo ha reso il processo un po\' più difficile. Detto ciò, la qualità del lavoro finale era comunque molto buona, e la puntualità con cui è stato completato è stata una nota positiva. Mi sento soddisfatto nel complesso, ma credo che ci sia ancora spazio per migliorare soprattutto nella fase iniziale del servizio, quando la chiarezza e la tempestività della comunicazione sono cruciali.',
        '2023-09-02', 4, 3, 4, 3, 3.75, 12, 14),

       ('La qualità del lavoro che ho ricevuto è stata al di sopra delle mie aspettative. Ogni fase del progetto è stata eseguita con grande attenzione ai dettagli, e la puntualità è stata impeccabile. Tuttavia, devo ammettere che il costo mi è sembrato un po\' alto rispetto ai risultati che ho ottenuto. Sebbene il lavoro fosse di buona qualità, il prezzo non era completamente giustificato. Inoltre, alcune opzioni di personalizzazione non erano così facili da implementare, e questo ha limitato un po\' la mia esperienza. In generale, il servizio è stato buono, ma il costo potrebbe essere un fattore da considerare per il futuro.',
        '2023-02-28', 4, 3, 4, 4, 3.75, 9, 8),

       ('Il servizio è stato davvero ottimo. La comunicazione è stata efficace, anche se c\'è stato un leggero ritardo nella consegna. Il costo è stato giusto e la qualità del lavoro era alta. Sono soddisfatto, anche se c\'è margine di miglioramento per la puntualità.',
        '2024-12-28', 5, 4, 5, 3, 4.25, 13, 3),

       ('Un servizio davvero eccezionale! Hanno rispettato tutte le tempistiche e il lavoro era di qualità. La comunicazione è stata perfetta e il costo assolutamente ragionevole. Non potrei essere più soddisfatto!',
        '2023-10-11', 5, 5, 5, 5, 5, 13, 4),

       ('Sono rimasto colpito dalla qualità del lavoro, ma ci sono stati problemi di comunicazione durante alcune fasi del progetto. Inoltre, i costi erano un po\' più alti di quanto mi aspettassi. Tuttavia, il risultato finale è stato buono.',
        '2024-06-04', 3, 3, 5, 4, 3.75, 13, 5),

       ('Ho trovato il servizio buono nel complesso. La comunicazione è stata buona e il lavoro completato nei tempi previsti. Tuttavia, la qualità finale non era esattamente come speravo e i costi erano leggermente elevati.',
        '2022-02-12', 4, 3, 4, 5, 4, 13, 6),

       ('Un team professionale che sa cosa fa! La comunicazione è stata chiara e il prodotto finale era eccellente. Peccato per un piccolo ritardo nella consegna, ma nel complesso sono molto soddisfatto!',
        '2024-07-11', 5, 5, 5, 4, 4.75, 13, 7),

       ('Non sono completamente soddisfatto del servizio. La qualità del lavoro era discreta, ma la comunicazione è stata carente e ci sono stati diversi ritardi. Purtroppo non credo che utilizzerò di nuovo questo servizio.',
        '2024-12-23', 2, 3, 3, 2, 2.5, 16, 8),

       ('Un servizio che consiglierei a chiunque! Il lavoro è stato svolto con grande cura e professionalità. Le tempistiche sono state rispettate e la comunicazione è stata impeccabile. Il costo è assolutamente proporzionato alla qualità ricevuta.',
        '2022-03-25', 5, 5, 5, 5, 5, 13, 9),

       ('Sono rimasto soddisfatto dal servizio, anche se c\'è stato un piccolo problema con la qualità finale. Tuttavia, il team si è mostrato disponibile a correggere l\'errore. La comunicazione è stata eccellente.',
        '2024-12-21', 5, 4, 3, 5, 4.25, 13, 10),

       ('Esperienza molto positiva! Nonostante qualche ritardo nella consegna, il lavoro era di qualità e il costo adeguato. La comunicazione potrebbe essere migliorata in alcune fasi, ma nel complesso sono soddisfatto.',
        '2023-11-20', 4, 4, 5, 3, 4, 13, 11),

       ('Il servizio è stato buono, ma non eccellente. La comunicazione è stata lenta in alcuni momenti e la qualità del lavoro, sebbene accettabile, non era al livello che mi aspettavo. Il costo era adeguato.',
        '2014-07-23', 3, 4, 4, 4, 3.75, 13, 12),

       ('Tutto perfetto, nessun problema, consiglio vivamente!', '2023-12-13', 5, 5, 5, 5, 5, 13, 15);

-- Query per inserire tutti i ticket -->
INSERT INTO ticket (ticket_requester_id, title, description, priority_flag, date, type, state, review_id, product_id,
                    reported_user_id)
VALUES (5, 'Richiesta di vendita sulla piattaforma',
        'Sono un cliente da tempo sulla piattaforma e ora vorrei iniziare a vendere i miei prodotti. Vi chiedo di aggiornare il mio profilo da acquirente a venditore e di abilitarmi alla vendita.',
        'MEDIUM', '2025-01-02 13:15:00', 'SELLER_REQUEST', 'In attesa', NULL, NULL, NULL),
       (7, 'Richiesta di upgrade a venditore',
        'Desidero passare dal mio attuale status di acquirente a quello di venditore per poter aprire il mio negozio online e vendere i miei prodotti sulla vostra piattaforma. Vi prego di aggiornare il mio profilo.',
        'MEDIUM', '2025-01-02 14:00:00', 'SELLER_REQUEST', 'In attesa', NULL, NULL, NULL),
       (17, 'Attivazione del profilo venditore',
        'Sono un acquirente da molto tempo e sono pronto a passare alla vendita. Voglio utilizzare la piattaforma per promuovere e vendere i miei prodotti, pertanto richiedo l’attivazione del mio profilo come venditore.',
        'HIGH', '2025-01-02 15:00:00', 'SELLER_REQUEST', 'In attesa', NULL, NULL, NULL),
       (16, 'Richiesta per diventare venditore',
        'Mi piacerebbe trasformare il mio account da acquirente a venditore sulla vostra piattaforma. Vorrei poter caricare i miei prodotti e iniziare a vendere. Vi chiedo di abilitarmi come venditore.',
        'MEDIUM', '2025-01-02 16:30:00', 'SELLER_REQUEST', 'In attesa', NULL, NULL, NULL),
       (15, 'Passaggio a profilo venditore',
        'Desidero aprire un negozio sulla vostra piattaforma per iniziare a vendere i miei prodotti. Attualmente sono un acquirente e chiedo di passare a venditore. Vi prego di abilitarmi e di fornirmi le istruzioni necessarie.',
        'HIGH', '2025-01-02 17:00:00', 'SELLER_REQUEST', 'In attesa', NULL, NULL, NULL),
       (14, 'Attivazione account venditore',
        'Ho recentemente deciso di iniziare a vendere i miei prodotti e vorrei passare al profilo venditore. Vi chiedo cortesemente di aggiornare il mio account per permettermi di iniziare a vendere sulla piattaforma.',
        'MEDIUM', '2025-01-02 17:30:00', 'SELLER_REQUEST', 'In attesa', NULL, NULL, NULL),
       (13, 'Richiesta per aprire negozio come venditore',
        'Sono un acquirente e ho deciso di aprire un negozio per vendere i miei prodotti sulla vostra piattaforma. Vi chiedo di cambiare il mio status da acquirente a venditore e di fornirmi le istruzioni per iniziare a vendere.',
        'HIGH', '2025-01-02 18:00:00', 'SELLER_REQUEST', 'In attesa', NULL, NULL, NULL),
       (12, 'Segnalazione recensione falsa',
        'Ho trovato una recensione falsa sul prodotto che ho acquistato. La recensione contiene informazioni errate e diffamatorie che non corrispondono al mio reale utilizzo del prodotto. Chiedo di rimuoverla dalla piattaforma.',
        'MEDIUM', '2025-01-02 10:00:00', 'REPORT_REVIEWS', 'Accettato', 1, NULL, NULL),
       (14, 'Recensione inappropriata',
        'La recensione sul prodotto XYZ contiene linguaggio offensivo e inappropriato. Chiedo che venga verificata e, se ritenuta violante delle politiche della piattaforma, venga rimossa.',
        'HIGH', '2025-01-02 11:00:00', 'REPORT_REVIEWS', 'In attesa', 2, NULL, NULL),
       (3, 'Recensione non corrispondente al prodotto',
        'La recensione del prodotto ABC non è pertinente al prodotto che ho acquistato. Penso che sia stata scritta per errore. Vi chiedo di verificare e rimuovere questa recensione se non è accurata.',
        'MEDIUM', '2025-01-02 12:30:00', 'REPORT_REVIEWS', 'In attesa', 3, NULL, NULL),
       (4, 'Segnalazione recensione con informazioni errate',
        'La recensione che appare per il prodotto DEF è completamente errata. Il recensore ha confuso le specifiche tecniche e ha fornito informazioni false. Vi chiedo di rimuoverla.',
        'HIGH', '2025-01-02 13:00:00', 'REPORT_REVIEWS', 'In attesa', 4, NULL, NULL),
       (5, 'Recensione con contenuti spam',
        'Ho trovato una recensione sul prodotto GHI che contiene solo link pubblicitari e promozionali senza alcun commento utile al prodotto stesso. Vi chiedo di rimuoverla immediatamente.',
        'MEDIUM', '2025-01-02 14:00:00', 'REPORT_REVIEWS', 'In attesa', 5, NULL, NULL),
       (6, 'Recensione contenente offese personali',
        'Una recensione per il prodotto JKL è stata scritta in modo molto offensivo nei confronti di un altro utente. Chiedo di indagare sul contenuto e di prendere provvedimenti appropriati.',
        'HIGH', '2025-01-02 15:30:00', 'REPORT_REVIEWS', 'In attesa', 6, NULL, NULL),
       (7, 'Recensione con valutazione errata',
        'La recensione sul prodotto MNO ha una valutazione di 1 stella ma il recensore ha scritto un commento positivo. Sospetto che si tratti di un errore. Chiedo di esaminare e correggere la valutazione.',
        'MEDIUM', '2025-01-02 16:00:00', 'REPORT_REVIEWS', 'In attesa', 7, NULL, NULL),
       (8, 'Segnalazione recensione duplicata',
        'Ho notato che una recensione per il prodotto PQR è stata pubblicata più volte dallo stesso utente. Chiedo di rimuovere la recensione duplicata.',
        'LOW', '2025-01-02 17:00:00', 'REPORT_REVIEWS', 'In attesa', 8, NULL, NULL),
       (9, 'Recensione con contenuto violento',
        'La recensione per il prodotto STU contiene un linguaggio violento e minaccioso. Vi chiedo di intervenire e rimuovere il contenuto offensivo dalla piattaforma.',
        'HIGH', '2025-01-02 17:30:00', 'REPORT_REVIEWS', 'In attesa', 9, NULL, NULL),
       (10, 'Recensione contenente materiale protetto da copyright',
        'Ho notato che una recensione contiene materiale protetto da copyright (immagini, testo) senza autorizzazione. Chiedo che venga rimossa per violazione dei diritti d\'autore.',
        'MEDIUM', '2025-01-02 18:00:00', 'REPORT_REVIEWS', 'In attesa', 10, NULL, NULL),
       (3, 'Segnalazione utente per comportamento scorretto',
        'L\'utente XYZ sta utilizzando linguaggio offensivo nei confronti di altri utenti sulla piattaforma. Vi chiedo di esaminare il suo comportamento e prendere i provvedimenti necessari.',
        'MEDIUM', '2025-01-02 10:00:00', 'REPORT_USER', 'Accettato', NULL, NULL, 12),
       (4, 'Segnalazione utente per truffa',
        'L\'utente ABC sta cercando di truffare altri acquirenti vendendo prodotti falsi. Vi chiedo di prendere provvedimenti per fermare questa attività fraudolenta.',
        'MEDIUM', '2025-01-02 11:00:00', 'REPORT_USER', 'In attesa', NULL, NULL, 14),
       (5, 'Utente che invia messaggi spam',
        'L\'utente DEF sta inviando messaggi di spam a tutti gli acquirenti sulla piattaforma. Chiedo che venga sospeso e che il suo comportamento venga monitorato.',
        'LOW', '2025-01-02 12:30:00', 'REPORT_USER', 'In attesa', NULL, NULL, 15),
       (6, 'Utente che viola le politiche della piattaforma',
        'L\'utente GHI sta vendendo prodotti che violano le politiche della piattaforma. Chiedo che il suo account venga sospeso fino a una verifica.',
        'HIGH', '2025-01-02 13:00:00', 'REPORT_USER', 'In attesa', NULL, NULL, 16),
       (7, 'Segnalazione utente per comportamento molesto',
        'L\'utente JKL ha iniziato a fare commenti molesti e provocatori sui miei acquisti. Vi chiedo di intervenire e bloccare questo comportamento.',
        'MEDIUM', '2025-01-02 14:00:00', 'REPORT_USER', 'Rifiutato', NULL, NULL, 17),
       (8, 'Abuso della funzione di feedback',
        'L\'utente MNO sta utilizzando il sistema di feedback per lasciare recensioni ingiustificate e dannose sui venditori. Chiedo che vengano presi provvedimenti.',
        'LOW', '2025-01-02 15:00:00', 'REPORT_USER', 'In attesa', NULL, NULL, 3),
       (9, 'Utente che fa uso di linguaggio offensivo',
        'L\'utente PQR ha usato un linguaggio altamente offensivo nei confronti di altri membri della community. Chiedo che venga esaminato e che venga sospeso.',
        'HIGH', '2025-01-02 16:30:00', 'REPORT_USER', 'In attesa', NULL, NULL, 4),
       (10, 'Segnalazione di un utente sospetto',
        'L\'utente STU ha un comportamento sospetto, sospetto di essere coinvolto in attività fraudolente. Vi chiedo di indagare su questo account e prendere provvedimenti.',
        'LOW', '2025-01-02 17:00:00', 'REPORT_USER', 'In attesa', NULL, NULL, 5),
       (11, 'Utente che pubblica contenuti violenti',
        'L\'utente VWX sta pubblicando contenuti violenti sulla piattaforma. Chiedo che venga sospeso e che venga avviata un\'indagine su questo comportamento.',
        'HIGH', '2025-01-02 17:30:00', 'REPORT_USER', 'In attesa', NULL, NULL, 6),
       (12, 'Segnalazione utente per frode',
        'L\'utente YZ ha tentato di commettere una frode durante una transazione. Ho le prove che l\'utente ha agito in malafede, e richiedo che venga sospeso dal sistema.',
        'HIGH', '2025-01-02 18:00:00', 'REPORT_USER', 'Rifiutato', NULL, NULL, 7),
       (1, 'Servizio fraudolento di animazione personalizzata',
        'Il servizio "Animazione Personalizzata per Video Promozionali" sembra essere fraudolento. I clienti hanno segnalato che i video consegnati non sono stati realizzati come promesso, e alcuni hanno persino ricevuto file generici che non corrispondono alle loro richieste. Richiedo una verifica approfondita di questo servizio.',
        'HIGH', '2025-01-02 10:00:00', 'REPORT_PRODUCT', 'In attesa', NULL, 1, NULL),
       (2, 'Recensione offensiva per il servizio di sviluppo applicazioni web',
        'Una recensione lasciata da un utente sul servizio "Sviluppo Applicazioni Web Personalizzate" è altamente offensiva e contiene commenti diffamatori. La recensione non è pertinente al servizio e ha come scopo danneggiare l\'immagine del fornitore del servizio. Chiedo la rimozione della recensione e un controllo sui contenuti.',
        'HIGH', '2025-01-02 12:00:00', 'REPORT_PRODUCT', 'In attesa', NULL, 2, NULL),
       (3, 'Attività fraudolente legate al servizio di ottimizzazione SEO',
        'Sono emerse segnalazioni di tentativi di frode legati al servizio "Ottimizzazione SEO per Siti Web". Gli utenti hanno ricevuto richieste non autorizzate di pagamento tramite canali esterni, utilizzando il nome del servizio. Chiedo un intervento urgente per fermare questa attività fraudolenta.',
        'LOW', '2025-01-02 14:00:00', 'REPORT_PRODUCT', 'In attesa', NULL, 3, NULL),
       (4, 'Servizio di fotografia professionale ingannevole',
        'Il servizio di "Fotografia Professionale di Prodotti" sta ricevendo segnalazioni di truffe da parte di alcuni utenti, che affermano di non aver mai ricevuto il servizio richiesto nonostante il pagamento effettuato. Chiedo un\'indagine approfondita e il blocco del servizio fino alla risoluzione del problema.',
        'LOW', '2025-01-02 15:30:00', 'REPORT_PRODUCT', 'In attesa', NULL, 4, NULL),
       (6, 'Recensione offensiva e diffamatoria',
        'Una recensione lasciata sul servizio di "Animazione Personalizzata per Video Promozionali" contiene contenuti offensivi e diffamatori, che non sono in alcun modo correlati alla qualità del servizio. Chiedo che la recensione venga rimossa immediatamente e che vengano prese misure contro l\'utente che l\'ha pubblicata.',
        'LOW', '2025-01-02 17:00:00', 'REPORT_REVIEWS', 'Rifiutato', 1, NULL, NULL),
       (7, 'Recensioni fraudolente per il servizio di sviluppo applicazioni web',
        'Sono state lasciate diverse recensioni false sul servizio "Sviluppo Applicazioni Web Personalizzate" da utenti che non hanno mai utilizzato il servizio. Queste recensioni sembrano essere state create per manipolare la reputazione del servizio. Chiedo che vengano rimosse e che venga avviato un controllo.',
        'LOW', '2025-01-02 18:00:00', 'REPORT_REVIEWS', 'In attesa', 2, NULL, NULL),
       (8, 'Recensione che viola le politiche del sito',
        'Una recensione pubblicata sul servizio di "Fotografia Professionale di Prodotti" contiene linguaggio inappropriato e minacce nei confronti del fornitore del servizio. La recensione non rispetta le politiche del sito e deve essere rimossa immediatamente.',
        'HIGH', '2025-01-02 19:00:00', 'REPORT_REVIEWS', 'In attesa', 3, NULL, NULL),
       (9, 'Comportamento fraudolento legato alle recensioni',
        'Un gruppo di account sospetti sta lasciando recensioni ingannevoli sul servizio di "Servizio di Traduzione Italiano-Inglese". Queste recensioni sembrano essere create per fare pubblicità al servizio tramite mezzi fraudolenti. Chiedo una revisione e una rimozione delle recensioni false.',
        'LOW', '2025-01-02 20:00:00', 'REPORT_REVIEWS', 'In attesa', 4, NULL, NULL),
       (10, 'Recensione non pertinente e diffamatoria',
        'Una recensione lasciata sul servizio "Ottimizzazione SEO per Siti Web" non riguarda affatto la qualità del servizio, ma attacca gratuitamente l\'azienda. La recensione è irrilevante e viola le regole del sito. Chiedo che venga rimossa e che vengano intraprese azioni per evitare casi simili in futuro.',
        'HIGH', '2025-01-02 21:00:00', 'REPORT_REVIEWS', 'Accettato', 5, NULL, NULL);

-- Query per inserire tutte le offerte -->
INSERT INTO offer (id, delivery_time_proposed, offer_date, price, score, auction_id, user_id)
VALUES (1, 15, '2024-12-10T10:00:00', 200,
        (0.4 * (1 - POW(200 / 250.0, 2))) + (0.4 * (1 / (1 + POW(15 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 1, 3),
       (2, 10, '2024-12-11T09:00:00', 180,
        (0.4 * (1 - POW(180 / 250.0, 2))) + (0.4 * (1 / (1 + POW(10 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 1, 4),
       (3, 20, '2024-12-12T14:00:00', 220,
        (0.4 * (1 - POW(220 / 250.0, 2))) + (0.4 * (1 / (1 + POW(20 / 15.0, 2)) + 0.1)) + (0.2 * (3 / 5.0)), 1, 5),
       (4, 7, '2024-12-06T10:00:00', 250,
        (0.4 * (1 - POW(250 / 250.0, 2))) + (0.4 * (1 / (1 + POW(7 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 2, 6),
       (5, 12, '2024-12-07T13:00:00', 240,
        (0.4 * (1 - POW(240 / 250.0, 2))) + (0.4 * (1 / (1 + POW(12 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 2, 7),
       (6, 5, '2024-12-08T16:00:00', 260,
        (0.4 * (1 - POW(260 / 250.0, 2))) + (0.4 * (1 / (1 + POW(5 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 2, 8),
       (7, 25, '2025-02-05T11:00:00', 500,
        (0.4 * (1 - POW(500 / 510.0, 2))) + (0.4 * (1 / (1 + POW(25 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 3, 9),
       (8, 30, '2025-02-06T14:00:00', 480,
        (0.4 * (1 - POW(480 / 510.0, 2))) + (0.4 * (1 / (1 + POW(30 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 3, 10),
       (9, 20, '2025-02-07T16:00:00', 520,
        (0.4 * (1 - POW(520 / 510.0, 2))) + (0.4 * (1 / (1 + POW(20 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 3, 11),
       (10, 8, '2025-01-30T09:00:00', 150,
        (0.4 * (1 - POW(150 / 250.0, 2))) + (0.4 * (1 / (1 + POW(8 / 15.0, 2)) + 0.1)) + (0.2 * (3 / 5.0)), 4, 12),
       (11, 12, '2025-01-31T10:00:00', 140,
        (0.4 * (1 - POW(140 / 250.0, 2))) + (0.4 * (1 / (1 + POW(12 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 4, 13),
       (12, 10, '2025-02-01T15:00:00', 160,
        (0.4 * (1 - POW(160 / 250.0, 2))) + (0.4 * (1 / (1 + POW(10 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 4, 14),
       (13, 10, '2024-12-11T10:00:00', 300,
        (0.4 * (1 - POW(300 / 250.0, 2))) + (0.4 * (1 / (1 + POW(10 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 5, 15),
       (14, 12, '2024-12-12T14:00:00', 280,
        (0.4 * (1 - POW(280 / 250.0, 2))) + (0.4 * (1 / (1 + POW(12 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 5, 16),
       (15, 15, '2024-12-13T17:00:00', 320,
        (0.4 * (1 - POW(320 / 250.0, 2))) + (0.4 * (1 / (1 + POW(15 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 5, 17),
       (16, 18, '2024-12-13T11:00:00', 190,
        (0.4 * (1 - POW(190 / 250.0, 2))) + (0.4 * (1 / (1 + POW(18 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 1, 13),
       (17, 25, '2024-12-14T10:00:00', 210,
        (0.4 * (1 - POW(210 / 250.0, 2))) + (0.4 * (1 / (1 + POW(25 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 1, 14),
       (18, 14, '2024-12-15T09:00:00', 205,
        (0.4 * (1 - POW(205 / 250.0, 2))) + (0.4 * (1 / (1 + POW(14 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 1, 15),
       (19, 14, '2024-12-14T11:00:00', 230,
        (0.4 * (1 - POW(230 / 250.0, 2))) + (0.4 * (1 / (1 + POW(14 / 15.0, 2)) + 0.1)) + (0.2 * (3 / 5.0)), 2, 16),
       (20, 16, '2024-12-16T12:00:00', 220,
        (0.4 * (1 - POW(220 / 250.0, 2))) + (0.4 * (1 / (1 + POW(16 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 2, 10),
       (21, 9, '2024-12-17T08:00:00', 240,
        (0.4 * (1 - POW(240 / 250.0, 2))) + (0.4 * (1 / (1 + POW(9 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 2, 11),
       (22, 22, '2025-02-07T16:00:00', 270,
        (0.4 * (1 - POW(270 / 250.0, 2))) + (0.4 * (1 / (1 + POW(22 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 3, 3),
       (23, 10, '2025-02-10T10:00:00', 300,
        (0.4 * (1 - POW(300 / 350.0, 2))) + (0.4 * (1 / (1 + POW(10 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 33, 3),
       (24, 12, '2025-02-11T09:00:00', 320,
        (0.4 * (1 - POW(320 / 350.0, 2))) + (0.4 * (1 / (1 + POW(12 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 33, 5),
       (25, 15, '2025-02-12T14:00:00', 340,
        (0.4 * (1 - POW(340 / 350.0, 2))) + (0.4 * (1 / (1 + POW(15 / 15.0, 2)) + 0.1)) + (0.2 * (3 / 5.0)), 33, 6),
       (26, 8, '2025-02-13T10:00:00', 310,
        (0.4 * (1 - POW(310 / 350.0, 2))) + (0.4 * (1 / (1 + POW(8 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 33, 7),
       (27, 14, '2025-02-14T13:00:00', 330,
        (0.4 * (1 - POW(330 / 350.0, 2))) + (0.4 * (1 / (1 + POW(14 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 33, 8),
       (28, 10, '2025-02-15T10:00:00', 400,
        (0.4 * (1 - POW(400 / 450.0, 2))) + (0.4 * (1 / (1 + POW(10 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 34, 11),
       (29, 12, '2025-02-16T09:00:00', 420,
        (0.4 * (1 - POW(420 / 450.0, 2))) + (0.4 * (1 / (1 + POW(12 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 34, 12),
       (30, 15, '2025-02-17T14:00:00', 440,
        (0.4 * (1 - POW(440 / 450.0, 2))) + (0.4 * (1 / (1 + POW(15 / 15.0, 2)) + 0.1)) + (0.2 * (3 / 5.0)), 34, 13),
       (31, 8, '2025-02-18T10:00:00', 410,
        (0.4 * (1 - POW(410 / 450.0, 2))) + (0.4 * (1 / (1 + POW(8 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 34, 14),
       (32, 14, '2025-02-19T13:00:00', 430,
        (0.4 * (1 - POW(430 / 450.0, 2))) + (0.4 * (1 / (1 + POW(14 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 34, 7),
       (33, 10, '2025-02-20T10:00:00', 500,
        (0.4 * (1 - POW(500 / 550.0, 2))) + (0.4 * (1 / (1 + POW(10 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 35, 7),
       (34, 12, '2025-02-21T09:00:00', 520,
        (0.4 * (1 - POW(520 / 550.0, 2))) + (0.4 * (1 / (1 + POW(12 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 35, 6),
       (35, 15, '2025-02-22T14:00:00', 540,
        (0.4 * (1 - POW(540 / 550.0, 2))) + (0.4 * (1 / (1 + POW(15 / 15.0, 2)) + 0.1)) + (0.2 * (3 / 5.0)), 35, 10),
       (36, 8, '2025-02-23T10:00:00', 510,
        (0.4 * (1 - POW(510 / 550.0, 2))) + (0.4 * (1 / (1 + POW(8 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 35, 11),
       (37, 14, '2025-02-24T13:00:00', 530,
        (0.4 * (1 - POW(530 / 550.0, 2))) + (0.4 * (1 / (1 + POW(14 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 35, 16),
       (38, 10, '2025-02-25T10:00:00', 600,
        (0.4 * (1 - POW(600 / 650.0, 2))) + (0.4 * (1 / (1 + POW(10 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 36, 5),
       (39, 12, '2025-02-26T09:00:00', 620,
        (0.4 * (1 - POW(620 / 650.0, 2))) + (0.4 * (1 / (1 + POW(12 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 36, 6),
       (40, 15, '2025-02-27T14:00:00', 640,
        (0.4 * (1 - POW(640 / 650.0, 2))) + (0.4 * (1 / (1 + POW(15 / 15.0, 2)) + 0.1)) + (0.2 * (3 / 5.0)), 36, 13),
       (41, 8, '2025-02-28T10:00:00', 610,
        (0.4 * (1 - POW(610 / 650.0, 2))) + (0.4 * (1 / (1 + POW(8 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 36, 15),
       (42, 14, '2025-03-01T13:00:00', 630,
        (0.4 * (1 - POW(630 / 650.0, 2))) + (0.4 * (1 / (1 + POW(14 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 36, 14),
       (43, 10, '2025-03-02T10:00:00', 700,
        (0.4 * (1 - POW(700 / 750.0, 2))) + (0.4 * (1 / (1 + POW(10 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 37, 3),
       (44, 12, '2025-03-03T09:00:00', 720,
        (0.4 * (1 - POW(720 / 750.0, 2))) + (0.4 * (1 / (1 + POW(12 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 37, 5),
       (45, 15, '2025-03-04T14:00:00', 740,
        (0.4 * (1 - POW(740 / 750.0, 2))) + (0.4 * (1 / (1 + POW(15 / 15.0, 2)) + 0.1)) + (0.2 * (3 / 5.0)), 37, 7),
       (46, 8, '2025-03-05T10:00:00', 710,
        (0.4 * (1 - POW(710 / 750.0, 2))) + (0.4 * (1 / (1 + POW(8 / 15.0, 2)) + 0.1)) + (0.2 * (4 / 5.0)), 37, 9),
       (47, 14, '2025-03-06T13:00:00', 730,
        (0.4 * (1 - POW(730 / 750.0, 2))) + (0.4 * (1 / (1 + POW(14 / 15.0, 2)) + 0.1)) + (0.2 * (5 / 5.0)), 37, 14);

-- Query per inserire tutte le iscrizioni alle aste -->
INSERT INTO auction_subscription (auction_id, user_id)
VALUES (1, 3),
       (1, 4),
       (1, 5),
       (1, 13),
       (1, 14),
       (1, 15),
       (2, 6),
       (2, 7),
       (2, 8),
       (2, 16),
       (2, 10),
       (2, 11),
       (3, 3),
       (3, 9),
       (3, 10),
       (3, 11),
       (4, 12),
       (4, 12),
       (4, 13),
       (4, 14),
       (5, 15),
       (5, 16),
       (5, 17),
       (33, 3),
       (33, 5),
       (33, 6),
       (33, 7),
       (33, 8),
       (34, 11),
       (34, 12),
       (34, 13),
       (34, 14),
       (34, 7),
       (35, 7),
       (35, 6),
       (35, 10),
       (35, 11),
       (35, 16),
       (36, 5),
       (36, 6),
       (36, 13),
       (36, 15),
       (36, 14),
       (37, 3),
       (37, 5),
       (37, 7),
       (37, 9),
       (37, 14);


